<?php
// Permission, nonce, event lifecycle and selective purge regression tests.
define('VERSION',isset($argv[1])?$argv[1]:'3.0.5.1');
$root=__DIR__.'/runtime/nav-'.getmypid();@mkdir($root.'/shop/admin',0700,true);@mkdir($root.'/cache',0700,true);
define('DIR_APPLICATION',$root.'/shop/admin/');define('DIR_CACHE',$root.'/cache/');define('DIR_STORAGE',$root.'/');define('DIR_IMAGE',$root.'/shop/image/');define('HTTPS_CATALOG','https://shop.example/');
require dirname(__DIR__).'/src/core/bootstrap.php';require dirname(__DIR__).'/src/adapters/admin.trait.php';
class NavUser {public $access=true,$modify=true;function hasPermission($kind,$route){return $kind==='access'?$this->access:$this->modify;}function getGroupId(){return 1;}}
class NavResponse {public $output,$headers=array();function addHeader($h){$this->headers[]=$h;}function setOutput($s){$this->output=$s;}}
class NavUrl {function link($route,$query,$ssl){return 'https://shop.example/admin/index.php?route='.$route.'&amp;'.$query;}}
class NavModel {public $events=array();function getSetting($code,$id){return array();}function deleteEvent($c){$this->events=array();}function deleteEventByCode($c){$this->events=array();}function addEvent($first,$trigger=null,$action=null,$status=null,$sort=null){$this->events[]=is_array($first)?$first:array('code'=>$first,'trigger'=>$trigger,'action'=>$action);}function addPermission($g,$kind,$r){}}
class NavLoader {function model($r){}}
class NavController {use FurMediaAdminActions;const FM_ROUTE='extension/module/furmedia_cache';public $user,$response,$url,$session,$request,$load,$model_setting_setting,$model_setting_event,$model_extension_event,$model_user_user_group;}
$c=new NavController();$c->user=new NavUser();$c->response=new NavResponse();$c->url=new NavUrl();$c->session=new stdClass();$c->session->data=array('user_token'=>'fixture','token'=>'fixture','fm_cache_nonce'=>'nonce');$c->request=new stdClass();$c->request->server=array('REQUEST_METHOD'=>'POST');$c->request->get=array();$c->request->post=array('operation'=>'status','fm_nonce'=>'nonce');$c->load=new NavLoader();$c->model_setting_setting=new NavModel();$c->model_setting_event=new NavModel();$c->model_extension_event=new NavModel();$c->model_user_user_group=new NavModel();
$n=0;function navCheck($ok,$label){global $n;$n++;if(!$ok)throw new Exception($label);}
$route='common/column_left';$data=array('menus'=>array());$c->navigation($route,$data);$c->navigation($route,$data);navCheck(count($data['menus'])===1,'navigation idempotent');$c->user->access=false;$data=array('menus'=>array());$c->navigation($route,$data);navCheck(!$data['menus'],'no access no menu');$c->quick();navCheck(!json_decode($c->response->output,true)['ok'],'access rejected');$c->user->access=true;$c->quick();navCheck(json_decode($c->response->output,true)['ok'],'status accepted');
$c->request->post['fm_nonce']='wrong';$c->request->post['operation']='purge';$c->quick();navCheck(!json_decode($c->response->output,true)['ok'],'bad nonce rejected');$c->request->post['fm_nonce']='nonce';$c->user->modify=false;$c->quick();navCheck(!json_decode($c->response->output,true)['ok'],'modify denied');$c->request->post['operation']='status';$c->quick();navCheck(json_decode($c->response->output,true)['ok'],'read-only status allowed');$c->user->modify=true;
$store=new \FurMedia\Cache\FileStore(DIR_CACHE.'furmedia_cache');$store->set('sql',array('x'=>1),60,array('sql'));$store->set('page','html',60,array('catalog'));$c->request->post['operation']='purge_sql';$c->quick();navCheck($store->get('sql')===null&&$store->get('page')==='html','selective SQL purge preserves other entries');$c->request->post['operation']='not_allowed';$c->quick();navCheck(!json_decode($c->response->output,true)['ok'],'unknown operation rejected');$c->request->server['REQUEST_METHOD']='GET';$c->quick();navCheck(!json_decode($c->response->output,true)['ok'],'GET rejected');
$c->install();$events=version_compare(VERSION,'3.0.0.0','<')?$c->model_extension_event:$c->model_setting_event;navCheck(count(array_filter($events->events,function($r){return $r['code']==='skynova_navigation';}))===2,'install adds two navigation events');$c->install();navCheck(count(array_filter($events->events,function($r){return $r['code']==='skynova_navigation';}))===2,'reinstall idempotent');
$output='<header></header>';$args=array();$c->toolbar($route,$args,$output);navCheck(strpos($output,'skynova-admin-nav')!==false,'toolbar renders');navCheck(strpos($output,'fetch(c.url')!==false,'POST controls');file_put_contents($root.'/toolbar.html',$output);
echo 'Admin navigation '.VERSION.': '.$n." assertions passed\n";
