<?php
use FurMedia\Cache\Settings;
$psi=new FurMedia\Cache\PageSpeed();
$recommendations=$psi->recommendations(array(
    'render-blocking-resources'=>array('score'=>0.2,'details'=>array('overallSavingsMs'=>1234)),
    'unminified-css'=>array('score'=>0.5,'details'=>array('overallSavingsBytes'=>20000)),
    'unminified-javascript'=>array('score'=>1),
    'font-display'=>array('score'=>0,'scoreDisplayMode'=>'notApplicable'),
    'unknown'=>array('score'=>0,'title'=>'<script>ignored</script>')
));
check(count($recommendations)===2 && $recommendations[0]['audit']==='render-blocking-resources','recommendations measured, bounded and prioritized');
check($recommendations[1]['savings_bytes']===20000.0,'recommendation savings preserved');
$report=$psi->report(array('categories'=>array('performance'=>array('score'=>0.75)),'audits'=>array('first-contentful-paint'=>array('displayValue'=>'1.2 s'))),'https://shop.example');
check($report['score']===75 && $report['metrics']['first-contentful-paint']==='1.2 s','PageSpeed report parsed offline');
check($report['recommendations']===array(),'missing opportunities produce no invented recommendation');
$batchRoot=$tmp.'/batch-shop';mkdir($batchRoot.'/catalog/view/theme/test',0755,true);mkdir($batchRoot.'/image/cache',0755,true);mkdir($batchRoot.'/extension',0755,true);
file_put_contents($batchRoot.'/catalog/view/theme/test/a.js','var batchValue = 123; // original');
file_put_contents($batchRoot.'/catalog/view/theme/test/a.css','body { color: blue; }');
file_put_contents($batchRoot.'/image/cache/ignored.png','not image');
file_put_contents($batchRoot.'/image/product.png','unsupported content');
$batchSettings=Settings::normalize(array('css_minify'=>1,'js_minify'=>1,'reserve_mb'=>0));
$batch=new FurMedia\Cache\Batch($tmp.'/batch-private',$batchRoot,'https://shop.example/',$batchSettings);
check($batch->status()['status']==='idle','batch idle state');
$batch->start('minify');$state=$batch->step(1);
check($state['processed']===1 && $state['status']==='run','batch processes bounded number of files');
$resume=new FurMedia\Cache\Batch($tmp.'/batch-private',$batchRoot,'https://shop.example/',$batchSettings);
$state=$resume->step(1);
check($state['status']==='done' && $state['processed']===2 && $state['generated']===2,'batch resumes persistent state and minifies both assets');
check(file_get_contents($batchRoot.'/catalog/view/theme/test/a.js')==='var batchValue = 123; // original','batch preserves original');
$batch->start('images');$state=$batch->step(10);
check($state['status']==='done' && $state['processed']===1 && $state['skipped']===1,'batch ignores generated cache and preserves unsupported image');
$batch->start('minify');$state=$batch->cancel();check($state['status']==='cancelled' && !isset($state['files']),'batch cancellation removes pending work');
$bad=false;try{$batch->start('../outside');}catch(Exception $e){$bad=true;}check($bad,'batch kind allowlist');
$batch->start('minify');$changed=$batchSettings;$changed['quality']=60;
$bad=false;try{(new FurMedia\Cache\Batch($tmp.'/batch-private',$batchRoot,'https://shop.example/',$changed))->step();}catch(Exception $e){$bad=true;}check($bad,'batch does not mix settings across resumed steps');$batch->cancel();
$rulesSettings=Settings::normalize(array('status'=>1,'mode'=>'session','page_rules'=>'{"product/product":{"ttl":40,"logged":true,"cart":true}}'));
$ruleRequest=array('method'=>'GET','route'=>'product/product','uri'=>'/products/item','query'=>array('product_id'=>7),'authorization'=>false,'ajax'=>false,'range'=>false);
$ruleContext=array('session_id'=>'one','customer'=>true,'cart'=>true);
check((new FurMedia\Cache\Policy())->reason($ruleRequest,$ruleContext,$rulesSettings)==='','explicit read-only private customer and cart rule');
check(FurMedia\Cache\PageRules::ttl($rulesSettings,'product/product')===40 && FurMedia\Cache\PageRules::ttl($rulesSettings,'common/home')===300,'per-route TTL with default fallback');
$rulesSettings['logged_exclude_urls']='/products/*';check((new FurMedia\Cache\Policy())->reason($ruleRequest,$ruleContext,$rulesSettings)==='logged-url-exclude','logged URL exclusion');
$ruleRequest['route']='checkout/cart';$rulesSettings['routes'].="\ncheckout/cart";$rulesSettings['page_rules']='{"checkout/cart":{"logged":true,"cart":true}}';
check((new FurMedia\Cache\Policy())->reason($ruleRequest,$ruleContext,$rulesSettings)==='sensitive-route','private rules cannot override checkout guard');
$bad=false;try{Settings::normalize(array('page_rules'=>'{"common/home":{"unexpected":true}}'));}catch(Exception $e){$bad=true;}check($bad,'unknown rule fields rejected');
$bad=false;try{Settings::normalize(array('include_urls'=>'https://evil.example'));}catch(Exception $e){$bad=true;}check($bad,'URL rules reject external origins');
$matrix=FurMedia\Cache\WarmVariants::parse('{"languages":["ro-ro","en-gb"],"currencies":["RON","EUR"],"agents":["Desktop fixture","Mobile fixture"]}');
check(count($matrix)===8 && $matrix[0]['headers']===array('Cookie: language=ro-ro; currency=RON','User-Agent: Desktop fixture'),'crawler language currency device matrix');
$bad=false;try{FurMedia\Cache\WarmVariants::parse('{"agents":["Injected\r\nAuthorization: secret"]}');}catch(Exception $e){$bad=true;}check($bad,'crawler header injection rejected');
$variantCalls=array();$variantQueue=new FurMedia\Cache\WarmQueue($tmp.'/variant-queue','https://shop.example',function($url,$headers)use(&$variantCalls){$variantCalls[]=$headers;return array('body'=>'ok');});
$variantResult=$variantQueue->run(array('paths'=>array('/'),'variants'=>'{"languages":["ro-ro","en-gb"],"currencies":["RON","EUR"]}','limit'=>10));
check($variantResult['fetched']===4 && count(array_unique(array_map('serialize',$variantCalls)))===4,'crawler fetches every language currency combination separately');
$inline='window.skynovaInline = 7;';$scriptSettings=Settings::normalize(array('extract_js'=>1,'script_position'=>'bottom','script_allow'=>'sha256:'.hash('sha256',$inline)));
$scriptAssets=new FurMedia\Cache\Assets($batchRoot,$batchRoot.'/image/cache/furmedia_cache','https://shop.example/',$scriptSettings);
$scriptHtml='<html><head><script>'.$inline.'</script></head><body><div>content</div></body></html>';
$scriptResult=(new FurMedia\Cache\Optimizer($scriptSettings,$scriptAssets))->transform($scriptHtml);
check(strpos($scriptResult,$inline)===false && preg_match('~<div>content</div><script src="https://shop.example/image/cache/furmedia_cache/[a-f0-9]{64}.js"></script></body>~',$scriptResult),'approved inline script extracted and positioned at bottom');
$inventory=FurMedia\Cache\Scripts::inventory($scriptHtml.'<pre><script>ignored();</script></pre><script type="application/ld+json">{}</script>');
check(count($inventory)===2 && !$inventory[0]['blocked'] && $inventory[1]['blocked'],'script inventory protects raw text and non-JavaScript');
$unsafe='document.write("unsafe");';$scriptSettings['script_allow']='sha256:'.hash('sha256',$unsafe);
$unsafeHtml='<html><head><script>'.$unsafe.'</script></head><body></body></html>';
check(FurMedia\Cache\Scripts::transform($unsafeHtml,$scriptAssets,$scriptSettings)===$unsafeHtml,'document.write never extracted or relocated');
$scriptSettings['script_allow']='sha256:'.hash('sha256',$inline);$missing='<script>'.$inline.'</script>';
check(FurMedia\Cache\Scripts::transform($missing,$scriptAssets,$scriptSettings)===$missing,'missing insertion boundary preserves original scripts');
$vault=new FurMedia\Cache\Vault($tmp.'/vault');$vault->save(array('SKYNOVA_CF_TOKEN'=>'fixture-secret-value','SKYNOVA_CF_ZONE'=>str_repeat('a',32)),2);
check($vault->read(2)['SKYNOVA_CF_TOKEN']==='fixture-secret-value' && $vault->read(0)===array(),'encrypted vault roundtrip and store separation');
check(strpos(file_get_contents($tmp.'/vault/store-2.vault'),'fixture-secret-value')===false,'vault never stores plaintext credential');
$vault->save(array('SKYNOVA_CF_TOKEN'=>''),2);check($vault->read(2)['SKYNOVA_CF_TOKEN']==='fixture-secret-value','blank admin credential preserves existing secret');
$vault->save(array(),2,array('SKYNOVA_CF_TOKEN'));check(!isset($vault->read(2)['SKYNOVA_CF_TOKEN']),'explicit credential removal');
$raw=file_get_contents($tmp.'/vault/store-2.vault');$raw[40]=chr(ord($raw[40])^1);file_put_contents($tmp.'/vault/store-2.vault',$raw);
$bad=false;try{$vault->read(2);}catch(Exception $e){$bad=true;}check($bad,'vault detects ciphertext tampering');
$resourceHeaders=FurMedia\Cache\Resources::headers(array('Content-Type: text/css; charset=utf-8','ETag: "fixture"','Last-Modified: Tue, 01 Jan 2030 00:00:00 GMT','X-Unsafe: ignored'),200);
check(in_array('ETag: "fixture"',$resourceHeaders,true) && !in_array('X-Unsafe: ignored',$resourceHeaders,true) && in_array('Cache-Control: private, no-store',$resourceHeaders,true),'dynamic resource response metadata cached with private policy');
check(FurMedia\Cache\Resources::headers(array('Content-Type: text/css','Set-Cookie: private=secret'),200)===false,'dynamic resource cookies never cached');
check(FurMedia\Cache\Resources::headers(array('Content-Type: text/html'),200)===false && FurMedia\Cache\Resources::headers(array('Content-Type: text/css'),404)===false,'dynamic resource type and status admission');
$resourceSettings=Settings::normalize(array('dynamic_cache'=>1,'dynamic_urls'=>'/index.php?route=extension/demo/module/css'));
$resourceRequest=$ruleRequest;$resourceRequest['route']='extension/demo/module/css';$resourceRequest['uri']=$resourceSettings['dynamic_urls'];$resourceContext=array('session_id'=>'guest');
check(FurMedia\Cache\Resources::eligible($resourceRequest,$resourceContext,$resourceSettings),'exact approved dynamic controller admitted');
$resourceContext['customer']=true;check(!FurMedia\Cache\Resources::eligible($resourceRequest,$resourceContext,$resourceSettings),'dynamic resource authenticated response bypass');
check((new FurMedia\Cache\Policy())->responseAllowed('<html>missing</html>',array('HTTP/1.1 404 Not Found'),404,true),'explicit 404 admission preserves matching status');
check(!(new FurMedia\Cache\Policy())->responseAllowed('<html>missing</html>',array('HTTP/1.1 404 Not Found'),200,true),'mismatched status never cached');
$ls=FurMedia\Cache\Litespeed::headers(200,array('catalog','product:7'), 'OCSESSID',true);
check(strpos($ls[0],'private,max-age=200,esi=on')!==false && strpos($ls[1],'public:sn_')!==false,'LiteSpeed private cache and public invalidation tag protocol');
check(strpos(FurMedia\Cache\Litespeed::purge('product:7'),'private,*')!==false,'LiteSpeed purge includes current private cache');
$esiContext=array('session_id'=>'one','store'=>0,'currency'=>'RON','language'=>'1','customer'=>false,'cart'=>false);
$esi=new FurMedia\Cache\Esi($tmp.'/esi','{"extension/module/fixture":{"scope":"private","ttl":30,"args":[]}}');
$include=$esi->includeModule('extension/module/fixture',array(),'<div>module</div>',$esiContext,'generation-one','/index.php?route=extension/module/furmedia_cache/esi');
check(strpos($include,'<esi:include')===0 && strpos($include,'<esi:remove><div>module</div></esi:remove>')!==false,'ESI includes native fallback');
preg_match('/&amp;id=([a-f0-9]+)&amp;signature=([a-f0-9]+)/',$include,$esiMatch);
$descriptor=$esi->descriptor($esiMatch[1],$esiMatch[2],$esiContext,'generation-one');
check($descriptor['route']==='extension/module/fixture','ESI signed descriptor resolves approved module');
$bad=false;try{$esi->descriptor($esiMatch[1],str_repeat('0',64),$esiContext,'generation-one');}catch(Exception $e){$bad=true;}check($bad,'ESI signature forgery rejected');
$other=$esiContext;$other['session_id']='two';$bad=false;try{$esi->descriptor($esiMatch[1],$esiMatch[2],$other,'generation-one');}catch(Exception $e){$bad=true;}check($bad,'private ESI descriptor bound to native session context');
$bad=false;try{$esi->descriptor($esiMatch[1],$esiMatch[2],$esiContext,'generation-two');}catch(Exception $e){$bad=true;}check($bad,'ESI generation invalidation');
$bad=false;try{FurMedia\Cache\Esi::parse('{"common/cart":{"scope":"public"}}');}catch(Exception $e){$bad=true;}check($bad,'cart cannot become public ESI');
check(FurMedia\Cache\Esi::headers($descriptor,'<form><input name="token"></form>',array())===array('X-LiteSpeed-Cache-Control: no-cache'),'tokenized ESI remains dynamic');
$variantQueue->pause(true);$beforeCalls=count($variantCalls);check($variantQueue->run(array('paths'=>array('/')))['paused'] && count($variantCalls)===$beforeCalls,'crawler pause prevents network requests');
$variantQueue->pause(false);check(!$variantQueue->status()['paused'],'crawler resumes persistent control');
check(FurMedia\Cache\Litespeed::device('Mozilla iPhone Safari')==='mobile-safari' && FurMedia\Cache\Litespeed::device('Mozilla Chrome Safari')==='desktop','device profiles distinguish Safari and mobile');
check(strpos(FurMedia\Cache\Widgets::script('/index.php?route=fixture',60),'credentials:"same-origin"')!==false,'widget refresh keeps native session and same origin');
$autoEsi=new FurMedia\Cache\Esi($tmp.'/esi-auto','{"extension/module/fixture":{"scope":"private"}}');
$autoInclude=$autoEsi->includeModule('extension/module/fixture',array(array('module_id'=>12,'limit'=>5)),'<div>native args</div>',$esiContext,'generation-one','/index.php?route=esi');
preg_match('/&amp;id=([a-f0-9]+)&amp;signature=([a-f0-9]+)/',$autoInclude,$autoMatch);
$autoRow=$autoEsi->descriptor($autoMatch[1],$autoMatch[2],$esiContext,'generation-one');check($autoRow['args']===array(array('module_id'=>12,'limit'=>5)),'ESI captures signed native invocation arguments automatically');
$publicEsi=new FurMedia\Cache\Esi($tmp.'/esi-public','{"extension/module/fixture":{"scope":"public"}}');
check($publicEsi->includeModule('extension/module/fixture',array(),'<div>module</div>',$esiContext,'generation-one','/index.php?route=esi')==='<div>module</div>','public ESI requires explicit clean guest context');
$nativeToken=str_repeat('a',26);$nativeBody='<html><a href="index.php?route=account/account&amp;customer_token='.$nativeToken.'">Account</a></html>';
check((new FurMedia\Cache\Policy())->responseAllowed($nativeBody,array(),200,false,$nativeToken),'private native customer token link accepted only for exact current token');
check(!(new FurMedia\Cache\Policy())->responseAllowed($nativeBody,array(),200,false,str_repeat('b',26)) && !(new FurMedia\Cache\Policy())->responseAllowed($nativeBody,array(),200),'foreign or public customer token remains blocked');
check(!(new FurMedia\Cache\Policy())->responseAllowed(str_replace('</html>','<script nonce="once"></script></html>',$nativeBody),array(),200,false,$nativeToken),'native link exception does not permit nonce replay');
$tokenRequest=array('method'=>'GET','route'=>'product/product','uri'=>'/index.php?route=product/product','query'=>array('customer_token'=>$nativeToken),'authorization'=>false,'ajax'=>false,'range'=>false);
$tokenContext=array('session_id'=>'native-token-session','customer'=>true,'customer_token_hash'=>hash('sha256',$nativeToken));
$tokenSettings=Settings::normalize(array('status'=>1,'page_rules'=>'{"product/product":{"logged":true}}'));
check((new FurMedia\Cache\Policy())->reason($tokenRequest,$tokenContext,$tokenSettings)==='','native logged token query accepted only for matching current session');
$tokenRequest['query']['customer_token']=str_repeat('b',26);check((new FurMedia\Cache\Policy())->reason($tokenRequest,$tokenContext,$tokenSettings)==='query','foreign native token query refused');
check($autoEsi->includeModule('extension/module/fixture',array(new stdClass()),'<div>original object args</div>',$esiContext,'generation-one','/index.php?route=esi')==='<div>original object args</div>','ESI preserves native object arguments instead of changing their type');
$bad=false;try{FurMedia\Cache\PageRules::parse('{"common/home":{"logged":"false"}}');}catch(Exception $e){$bad=true;}check($bad,'ambiguous string page rule flag rejected');

$diagnosticHistory=new FurMedia\Cache\History($tmp.'/diagnostic-history');
for($i=0;$i<35;$i++){$diagnosticHistory->append('diagnostic',array('status'=>'HIT','route'=>'common/home','store'=>0));}
check(count($diagnosticHistory->rows('diagnostic'))===30,'diagnostic history bounded to thirty route-only records');
$debugSettings=Settings::normalize(array('debug_details'=>1,'debug_session_hash'=>str_repeat('A',64)));
check($debugSettings['debug_details']===1 && $debugSettings['debug_session_hash']===str_repeat('a',64),'diagnostic selector accepts normalized SHA256 only');
