<?php
// Real Journal Document API; proprietary source stays outside this repository.
namespace { define('VERSION','3.0.5.1');define('JOURNAL3_VERSION','3.2.10');require dirname(__DIR__).'/src/core/bootstrap.php';require $argv[1].'/system/library/journal3/document.php'; }
namespace { class ControllerJournal3EventLayout {private static $layout=array();private static $layout_id=0; public static function seed($layout,$id){self::$layout=$layout;self::$layout_id=$id;} public static function state(){return self::$layout;} }
class JPRegistry {public $items=array();function get($key){return $this->items[$key];}function has($key){return isset($this->items[$key]);}}
class JPSettings {public $items=array();function get($key){return isset($this->items[$key])?$this->items[$key]:null;}function set($key,$v){$this->items[$key]=$v;}}
$r=new JPRegistry();$r->items['journal3_document']=new \Journal3\Document();$r->items['journal3']=new JPSettings();$doc=$r->items['journal3_document'];$doc->addClass('android');$doc->addCss('.base{color:black}','base');$doc->addJs(array('isPhone'=>true));$base=\FurMedia\Cache\JournalState::baseline($r);
$doc->addClass('layout-1');$doc->addCss('.module-34{height:400px}','slider');$doc->addJs(array('columnsCount'=>0,'slider'=>array('autoplay'=>true)));$doc->setPageRoute('common/home');$doc->setPageId(0);ControllerJournal3EventLayout::seed(array('bottom'=>'<div class="newsletter">Hello</div>','content_top'=>'<section>Body</section>'),1);
$r->items['journal3']->set('layout_id',1);$state=\FurMedia\Cache\JournalState::capture($r,$base);
$n=0;function check($v,$label){global $n;$n++;if(!$v){throw new \Exception($label);}}
check(is_array($state),'presentation captured');check(count($state['css'])===1,'body CSS delta only');check(!isset($state['classes']['android']),'browser classes not cached');check(!isset($state['js']['isPhone']),'runtime flags not cached');check(!isset($state['layout']['content_top']),'body not duplicated');
$r->items['journal3_document']=new \Journal3\Document();$fresh=$r->items['journal3_document'];$fresh->addClass('iphone');$fresh->addJs(array('isPhone'=>true));ControllerJournal3EventLayout::seed(array(),0);\FurMedia\Cache\JournalState::restore($r,$state);
check(isset($fresh->getClasses()['iphone']),'current browser class retained');check(!isset($fresh->getClasses()['android']),'other browser class not replayed');check(isset($fresh->getClasses()['layout-1']),'page class restored');check(count($fresh->getCss())===1,'body CSS restored');check($fresh->getJs()['slider']['autoplay']===true,'module init restored');check($r->items['journal3']->get('layout_id')===1,'layout selection restored');check(isset(ControllerJournal3EventLayout::state()['bottom']),'bottom layout preserved');
$unsafe=$state;$unsafe['js']['csrf']='secret';check(!\FurMedia\Cache\JournalState::safe($unsafe),'token key rejected');$unsafe=$state;$unsafe['layout']['bottom']='<input name="csrf" value="secret">';check(!\FurMedia\Cache\JournalState::safe($unsafe),'token markup rejected');$unsafe=$state;$unsafe['fonts']=new \stdClass();check(!\FurMedia\Cache\JournalState::safe($unsafe),'objects rejected');class JPDocument {function setTitle($v){} function setDescription($v){} function setKeywords($v){} function addLink($a,$b){} function addStyle($a,$b,$c){} function addScript($a,$b){}}
class JPLoad {public $registry;public $order=array();function __construct($r){$this->registry=$r;}function controller($route){$this->order[]=$route;$d=$this->registry->get('journal3_document');if($route==='common/footer'){$d->addCss('.fresh-footer{display:grid}','fresh-footer');return '<footer>Native</footer>';}return '<header>'.json_encode($d->getCss()).'</header>';}}
$r->items['document']=new JPDocument();$r->items['load']=new JPLoad($r);$entry=array('shell'=>'<!--skynova-dynamic-header--><main>Body</main><!--skynova-dynamic-footer-->','journal'=>$state,'document'=>array('Title'=>'Test','Description'=>'','Keywords'=>'','Links'=>array(),'Styles'=>array(),'scripts'=>array()));
$timings=array();$html=\FurMedia\Cache\SharedPage::render($entry,$r,$timings);check($r->items['load']->order===array('common/footer','common/header'),'native footer before header');check(strpos($html,'.module-34')!==false,'cached body module CSS reaches fresh header');check(strpos($html,'.fresh-footer')!==false,'fresh footer CSS reaches header');check(strpos($html,'<main>Body</main>')!==false,'cached body retained');
$old=$entry;unset($old['journal']);$refused=false;try{\FurMedia\Cache\SharedPage::render($old,$r);}catch(\RuntimeException $e){$refused=true;}check($refused,'old incomplete Journal entry refused');
echo 'PASS '.$n." native Journal presentation checks\n";
}
