<?php
namespace FurMedia\Cache;

class Admin {
    public static function e($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
    public static function schema() {
        return array(
            'general'=>array('title'=>'Control general','description'=>'Pornește cu Observare. Activează cache-ul după verificarea magazinului.', 'fields'=>array(
                'search_acceleration'=>array('Index auxiliar pentru căutări simple native (experimental)','bool'), 'view_stats'=>array('Numără afișări agregate pentru pagini publice','bool'), 'pwa_assets'=>array('Service worker pentru resurse publice generate','bool'), 'pwa_limit'=>array('Maximum resurse în cache-ul browserului','number'), 'pwa_cache_names'=>array('Nume exacte cache PWA deținute (unul per linie)','textarea'), 'db_archive_mb'=>array('Cotă arhive DB private (MB)','number'), 'db_schedules'=>array('Programări mentenanță DB (JSON)','textarea'), 'db_schedule_limit'=>array('Operații DB per CRON','number'), 'status'=>array('Modul activ','bool'), 'mode'=>array('Mod de funcționare','mode'), 'backend'=>array('Motor cache','backend'), 'journal'=>array('Protecție Journal 2 / 3','bool'), 'debug'=>array('Antet diagnostic X-FurMedia-Cache','bool'),'debug_details'=>array('Istoric diagnostic detaliat, maximum 30 evenimente','bool'),'debug_session_hash'=>array('SHA256 sesiune pentru diagnostic (gol = toate; vezi X-SkyNova-Session)','text'),
                'ttl'=>array('Valabilitate pagini (secunde)','number'), 'max_mb'=>array('Limită pe cache privat / resurse (MB fiecare)','number'), 'reserve_mb'=>array('Spațiu liber minim pe disc (MB)','number'), 'max_entry_kb'=>array('Mărime maximă pagină (KB)','number'))),
            'litespeed'=>array('title'=>'LiteSpeed și ESI','description'=>'Adaptor privat pentru pagini guest; necesită profilul private-v1 configurat în server. ESI necesită LiteSpeed Enterprise. Activarea în meniu singură nu autorizează cache public pentru pagini personalizate.', 'fields'=>array('device_vary'=>array('Grupează clienții: desktop / mobil / Safari / bot, numai pentru teme verificate','bool'),'litespeed'=>array('Adaptor LiteSpeed nativ','bool'),'litespeed_esi'=>array('Procesare ESI pentru module aprobate','bool'),'esi_modules'=>array('Module ESI JSON: scope, ttl, args (vezi ghidul)','textarea'))),
            'rules'=>array('title'=>'Pagini & excluderi','description'=>'Sesiunile private sunt izolate. Cache-ul comun necesită rute aprobate și tema standard. Contul, coșul și datele necunoscute sunt excluse.', 'fields'=>array('cache_404'=>array('Memorează răspunsuri 404 pe rutele aprobate, păstrând statusul','bool'),'ttl_404'=>array('Valabilitate 404 (secunde)','number'),'page_rules'=>array('Reguli JSON pe rută: ttl, enabled, logged, cart; numai pagini de catalog aprobate','textarea'),'include_urls'=>array('Include URL: căi exacte sau prefix terminat în * (gol = toate rutele aprobate)','textarea'),'exclude_urls'=>array('Exclude URL: căi exacte sau prefix terminat în *','textarea'),'logged_exclude_urls'=>array('Exclude URL pentru clienți autentificați','textarea'),'shared_routes'=>array('Rute aprobate pentru cache comun: tema standard, antet/subsol dinamice','textarea'),'routes'=>array('Rute publice permise, una pe linie','textarea'),'exclude_paths'=>array('Fragmente URL excluse','textarea'))),
            'assets'=>array('title'=>'CSS & JavaScript','description'=>'Resursele locale folosesc fișiere cu hash. Journal își păstrează pipeline-ul propriu când protecția este activă. Defer se aplică numai URL-urilor aprobate exact.', 'fields'=>array('dynamic_cache'=>array('Cache privat pentru răspunsuri CSS / JS dinamice','bool'),'dynamic_urls'=>array('URI exacte aprobate pentru resurse dinamice, inclusiv query string','textarea'),'dynamic_ttl'=>array('Valabilitate resurse dinamice (secunde)','number'),'extract_js'=>array('Extrage automat codul inline aprobat în fișiere JS','bool'),'script_position'=>array('Poziția scripturilor independente aprobate','position'),'script_allow'=>array('URL-uri locale exacte sau sha256:HASH pentru cod inline independent; păstrează ordinea între cele aprobate','textarea'),'css_merge'=>array('Combină CSS aprobat','bool'),'js_merge'=>array('Combină JavaScript aprobat','bool'),'merge_allow'=>array('URL-uri exacte aprobate pentru combinare (ordine nativă)','textarea'),'css_minify'=>array('Minificare CSS','bool'),'js_minify'=>array('Minificare JavaScript','bool'),'html_minify'=>array('Elimină comentariile HTML obișnuite','bool'),'defer_js'=>array('Defer pentru lista aprobată','bool'),'delay_js'=>array('Amână scripturi independente până la interacțiune / 4 secunde','bool'),'delay_allow'=>array('URL-uri exacte de scripturi independente pentru amânare','textarea'),'defer_allow'=>array('URL-uri exacte aprobate pentru defer','textarea'),'exclude_assets'=>array('Resurse excluse (fragmente URL)','textarea'),'critical_css'=>array('CSS critic verificat pentru această temă','textarea'),'gzip'=>array('Compresie gzip prin OpenCart','bool'))),
            'images'=>array('title'=>'Imagini & priorități','description'=>'Originalele rămân intacte. Conversia se aplică JPEG/PNG locale dacă GD suportă formatul și fișierul rezultat este mai mic. Primele două imagini nu primesc lazy loading.', 'fields'=>array('webp'=>array('Conversie WebP','bool'),'avif'=>array('Conversie AVIF dacă serverul permite','bool'),'responsive_images'=>array('Generează srcset 320/640/960/1280 (necesită WebP/AVIF)','bool'),'image_sizes'=>array('Atribut sizes pentru imagini noi','text'),'quality'=>array('Calitate conversie 0–100','number'),'image_dimensions'=>array('Completează dimensiunile lipsă','bool'),'lazy_images'=>array('Lazy loading nativ pentru imagini','bool'),'lazy_iframes'=>array('Lazy loading iframe','bool'),'preload_image'=>array('URL imagine principală pentru preload','text'),'preconnect'=>array('Origini HTTPS pentru preconnect','textarea'))),
            'cdn'=>array('title'=>'CDN & livrare','description'=>'CDN pull compatibil cu domenii proprii / CloudFront. Cloudflare proxy poate funcționa transparent. Nu sunt necesare chei CDN pentru rescrierea adreselor.', 'fields'=>array('cdn'=>array('Adresă HTTPS CDN (opțional)','text'))),
            'delivery'=>array('title'=>'Browser cache și compresie','description'=>'Durate pentru resurse statice: exportă profilul Apache/Nginx și integrează-l în configurația serverului. HTML personalizat rămâne no-store.', 'fields'=>array('browser_images'=>array('Imagini: secunde','number'),'browser_css'=>array('CSS: secunde','number'),'browser_js'=>array('JavaScript: secunde','number'),'browser_video'=>array('Video: secunde','number'),'browser_pdf'=>array('PDF: secunde','number'),'browser_fonts'=>array('Fonturi: secunde','number'),'prefetch_urls'=>array('Prefetch: URL public, unul pe linie','textarea'),'preload_urls'=>array('Preload: URL|font/style/script/image/fetch','textarea'),'compress_xml'=>array('Compresie XML','bool'),'compress_xhtml'=>array('Compresie XHTML','bool'),'compress_rss'=>array('Compresie RSS / Atom','bool'),'reserve_compressed'=>array('Reutilizează gzip pentru pagini admise, anonime, fără formulare/tokenuri','bool'),'cache_panel'=>array('Panou diagnostic în magazin (staging)','bool'),'panel_position'=>array('Poziție panou: left / right','text'),'panel_color'=>array('Fundal panou #RRGGBB','text'),'panel_text'=>array('Text panou #RRGGBB','text'),'panel_font'=>array('Mărime font panou 10–24 px','number'),'timezone'=>array('Fus orar pentru inventar, ex. Europe/Bucharest','text'))),
            'data'=>array('title'=>'Cache de date','description'=>'OpenCart 2.3 / 3: cache de rezultate pentru metodele de citire aprobate. OpenCart 4: această opțiune nu este activată de adaptor. Cache SQL selectiv pentru interogări exacte și cache pe componente izolat pe sesiune.', 'fields'=>array('dynamic_widgets'=>array('Actualizează coș / wishlist / comparație prin AJAX nativ (tema standard)','bool'),'widgets_interval'=>array('Interval actualizare widgeturi (secunde)','number'),'hide_category_count'=>array('Dezactivează numărul produselor din meniul nativ','bool'),'component_cache'=>array('Cache pe componente aprobate','bool'),'module_rules'=>array('Reguli JSON per rută și instanță module_id/layout_id (vezi ghidul)','textarea'),'component_allow'=>array('Rute de componente aprobate, una pe linie','textarea'),'component_ttl'=>array('Valabilitate componente (secunde)','number'),'sql_cache'=>array('Cache SQL selectiv','bool'),'sql_allow'=>array('Interogări SELECT exacte aprobate, una pe linie','textarea'),'sql_ttl'=>array('Valabilitate SQL (secunde)','number'),'model_cache'=>array('Cache de rezultate OC2.3 / OC3','bool'),'model_ttl'=>array('Valabilitate rezultate (secunde)','number'),'model_allow'=>array('Metode aprobate (vezi ghidul)','textarea'))),
            'advanced'=>array('title'=>'Reguli avansate','description'=>'Reguli exacte; scripturile aprobate trebuie să fie independente. Protecția Journal păstrează pipeline-ul temei.', 'fields'=>array('conditions'=>array('Condiții JSON: route, get, config, session, ttl, enabled','textarea'),'lazy_media'=>array('Video / audio fără autoplay: preload none','bool'),'lazy_blocks'=>array('ID-uri HTML pentru randare amânată','textarea'),'replacements'=>array('Înlocuiri JSON: find, replace, type html/css/js','textarea'),'resource_attributes'=>array('Atribute JSON pe URL exact','textarea'),'delay_rules'=>array('Amânare JSON pe URL: event, ms','textarea'),'custom_css'=>array('CSS personalizat','textarea'),'custom_js'=>array('JavaScript personalizat','textarea'),'custom_position'=>array('Poziție JS: top / bottom','text'),'external_assets'=>array('Mapare JSON URL extern → fișier local verificat','textarea'))),
'database'=>array('title'=>'Profilare și programare DB','description'=>'SELECT-uri anonimizate în catalog și panoul modulului. ANALYZE actualizează statistici, fără rescrierea SQL. Programarea folosește remote CRON din magazinul principal.', 'fields'=>array('sql_profile'=>array('Profilare SELECT','bool'),'sql_slow_ms'=>array('Prag lent (ms)','number'),'db_auto_analyze'=>array('ANALYZE automat, cel mult zilnic','bool'),'db_analyze_tables'=>array('Tabele cu prefix complet, maximum cinci','textarea'))),
'warm'=>array('title'=>'Preîncălzire & mentenanță','description'=>'Coada persistentă citește sitemap-uri, reia erorile și respectă intervalul configurat. Programați runnerul CLI la fiecare minut.', 'fields'=>array('warm_login'=>array('La prima cerere după login, pune URL-urile publice în coadă fără cookies ale clientului','bool'),'warm_variants'=>array('Variante JSON: languages, currencies, agents; maximum 32 combinații','textarea'),'warm_sitemaps'=>array('Sitemap-uri HTTPS de pe același magazin','textarea'),'warm_interval'=>array('Interval reîncălzire (secunde)','number'),'warm_urls'=>array('Căi relative de preîncălzit, una pe linie','textarea'),'warm_limit'=>array('Cereri maxime pe rulare','number')))
        );
    }

    public static function render(array $data) {
        $e = array(__CLASS__,'e'); $s = $data['settings'];
        ob_start();
        ?>
<div id="content"><style>
.fm{--ink:#14243a;--muted:#65758b;--line:#dce5ed;--accent:#177c70;font:14px/1.55 Arial,sans-serif;color:var(--ink);background:#f3f6f9;padding:28px;min-height:90vh}.fm *{box-sizing:border-box}.fm h1,.fm h2,.fm h3{color:var(--ink);font-weight:700}.fm h1{font-size:30px;margin:6px 0}.fm h2{font-size:20px;margin:0 0 12px}.fm p{color:var(--muted)}.fm-top{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:26px}.fm-kicker{letter-spacing:2px;text-transform:uppercase;font-size:11px;font-weight:700;color:var(--accent)}.fm-badge{background:#def1eb;color:#125c50;border:1px solid #b8e1d3;padding:6px 12px;border-radius:20px;font-size:12px;display:inline-block}.fm-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.fm-card,.fm-panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px}.fm-card strong{display:block;font-size:27px;margin:8px 0}.fm-card small{color:var(--muted)}.fm-layout{display:grid;grid-template-columns:210px 1fr;gap:22px}.fm-nav{position:sticky;top:18px;align-self:start}.fm-nav a{display:block;border-radius:8px;color:var(--muted);text-decoration:none;padding:12px;margin-bottom:4px}.fm-nav a:hover,.fm-nav a:focus{background:#e0eee9;color:#145f52}.fm-panel{margin-bottom:18px;scroll-margin-top:24px}.fm-row{display:grid;grid-template-columns:minmax(200px,1fr) minmax(180px,1fr);align-items:start;gap:20px;padding:15px 0;border-bottom:1px solid #eef2f6}.fm label{font-weight:500;padding-top:8px}.fm input:not([type=hidden]),.fm select,.fm textarea{width:100%;border:1px solid #cad5e0;border-radius:7px;padding:10px;background:#fff;color:var(--ink);font:inherit}.fm textarea{min-height:98px;font:12px/1.6 Consolas,monospace}.fm button,.fm-button{border:0;border-radius:8px;padding:11px 18px;font-weight:700;cursor:pointer;display:inline-block;background:var(--accent);color:white;text-decoration:none}.fm button.secondary{background:#e9eff4;color:#233e54}.fm-actions{display:flex;flex-wrap:wrap;gap:10px;margin:16px 0}.fm-note{border-left:4px solid #d8a24a;background:#fffaeb;padding:14px 18px;border-radius:5px;margin:16px 0}.fm-success{background:#def1eb;padding:14px;border-radius:8px}.fm-error{background:#ffe5e5;padding:14px;border-radius:8px;color:#a02121}.fm-table{width:100%;border-collapse:collapse}.fm-table td,.fm-table th{text-align:left;padding:12px;border-bottom:1px solid var(--line)}.fm code{color:#185d60;background:#edf6f4;padding:2px 5px}.fm-footer{color:var(--muted);font-size:12px;margin-top:24px}@media(max-width:900px){.fm-layout{grid-template-columns:1fr}.fm-nav{position:static;display:flex;flex-wrap:wrap}.fm-cards{grid-template-columns:repeat(2,1fr)}.fm-top{display:block}.fm-row{grid-template-columns:1fr;gap:4px}.fm{padding:16px}.fm h1{font-size:24px}}
</style>
<main class="fm">
<div class="fm-top"><div><div class="fm-kicker">SkyNova • Performance studio</div><h1>Cache Suite</h1><p>Control pentru viteză. Vizibilitate asupra fiecărei optimizări.</p></div><span class="fm-badge">0.6.0 • Development preview</span></div>
<?php if ($data['message']) { ?><div role="status" class="fm-success"><?= $e($data['message']) ?></div><?php } ?>
<?php if ($data['error']) { ?><div role="alert" class="fm-error"><?= $e($data['error']) ?></div><?php } ?>
<?php if(isset($data['stores'])) { ?><form method="get" action="index.php"><input type="hidden" name="route" value="<?= $e(isset($_GET['route'])?$_GET['route']:'') ?>"><?php foreach(array('user_token','token') as $token){if(isset($_GET[$token])){?><input type="hidden" name="<?= $e($token) ?>" value="<?= $e($_GET[$token]) ?>"><?php }} ?><label for="fm-store">Magazin</label><select id="fm-store" name="store_id"><?php foreach($data['stores'] as $row){?><option value="<?= (int)$row['store_id'] ?>" <?= (int)$row['store_id']===$data['store_id']?'selected':'' ?>><?= $e($row['name']) ?></option><?php } ?></select><button type="submit">Deschide magazinul</button></form><?php } ?>
<div class="fm-cards">
<?php foreach ($data['cards'] as $label=>$value) { ?><div class="fm-card"><small><?= $e($label) ?></small><strong><?= $e($value) ?></strong></div><?php } ?>
</div>
<div class="fm-note"><strong><?= $s['mode'] === 'observe' ? 'Mod observare: paginile nu sunt modificate sau servite din cache.' : ($s['mode']==='shared'?'Cache comun doar pe rute aprobate și tema standard. Journal folosește cache privat.':'Cache privat per sesiune: conținutul nu este distribuit între vizitatori.') ?></strong> Compatibilitatea completă se confirmă prin testarea temei, coșului și checkout-ului în staging.</div>
<form action="<?= $e($data['action']) ?>" method="post"><input type="hidden" name="fm_nonce" value="<?= $e($data['nonce']) ?>">
<div class="fm-layout"><nav class="fm-nav" aria-label="Setări Cache Suite">
<?php foreach (self::schema() as $id=>$section) { ?><a href="#fm-section-<?= $e($id) ?>"><?= $e($section['title']) ?></a><?php } ?><a href="#fm-warm-control">Control preîncălzire</a><a href="#fm-integrations">Integrări externe</a><a href="#fm-scripts">Inventar JavaScript</a><a href="#fm-batch">Procesare în lot</a><a href="#fm-diagnostic-log">Istoric diagnostic</a><a href="#fm-health">Diagnostic și PageSpeed</a><a href="#fm-inventory">Module și inventar</a><a href="#fm-database-tools">Instrumente DB</a><a href="#fm-external-import">Import extern</a><a href="#fm-maintenance">Mentenanță</a>
</nav><div>
<?php foreach (self::schema() as $id=>$section) { ?><section class="fm-panel" id="fm-section-<?= $e($id) ?>"><h2><?= $e($section['title']) ?></h2><p><?= $e($section['description']) ?></p>
<?php foreach ($section['fields'] as $key=>$field) { ?><div class="fm-row"><label for="fm-<?= $e($key) ?>"><?= $e($field[0]) ?></label><div>
<?php if (in_array($field[1],array('bool','mode','backend','position'),true)) { $choices = $field[1] === 'position' ? array('native'=>'Poziție nativă','top'=>'Sfârșitul antetului','bottom'=>'Sfârșitul paginii') : ($field[1] === 'bool' ? array(0=>'Dezactivat',1=>'Activat') : ($field[1]==='backend'?Drivers::choices():array('observe'=>'Observare','session'=>'Cache privat per sesiune','shared'=>'Cache comun aprobat / fallback privat'))); ?><select id="fm-<?= $e($key) ?>" name="settings[<?= $e($key) ?>]">
<?php foreach ($choices as $value=>$label) { ?><option value="<?= $e($value) ?>" <?= (string)$s[$key] === (string)$value ? 'selected' : '' ?>><?= $e($label) ?></option><?php } ?></select>
<?php } elseif ($field[1] === 'textarea') { ?><textarea id="fm-<?= $e($key) ?>" name="settings[<?= $e($key) ?>]" spellcheck="false"><?= $e($s[$key]) ?></textarea>
<?php } else { ?><input id="fm-<?= $e($key) ?>" type="<?= $e($field[1]) ?>" name="settings[<?= $e($key) ?>]" value="<?= $e($s[$key]) ?>"><?php } ?>
</div></div><?php } ?></section><?php } ?>
<?php echo AdvancedAdmin::render($data); echo SuiteAdmin::render($data); ?><section class="fm-panel" id="fm-warm-control"><h2>Control preîncălzire</h2><?php if(!empty($data['cron_url'])){ ?><p>Remote CRON: <code style="overflow-wrap:anywhere"><?= $e($data['cron_url']) ?></code>. Trimite POST prin HTTPS cu antetul Authorization: Bearer și secretul configurat în Integrări externe. Endpointul rulează preîncălzire, lotul activ și GC; maximum o rulare/minut. Secretul nu se pune în URL.</p><?php } ?><div class="fm-actions"><button class="secondary" name="operation" value="litespeed_profile">Exportă cerințele profilului LiteSpeed</button></div><p>Coada respectă magazinul, variantele și intervalul salvat. Oprirea afectează și runnerul CRON pentru aceeași configurație. Pe un magazin cu HTTP, folosește testele locale; runnerul de producție acceptă numai HTTPS public.</p><div class="fm-actions"><button name="operation" value="warm_run">Rulează un lot</button><button class="secondary" name="operation" value="warm_pause">Oprește coada</button><button class="secondary" name="operation" value="warm_resume">Reia coada</button></div><?php if(!empty($data['warm'])){?><p>Stare: <?= $data['warm']['paused']?'Oprită':'Activă' ?> · <?= (int)$data['warm']['total'] ?> joburi · <?= (int)$data['warm']['pending'] ?> în așteptare · <?= (int)$data['warm']['retry_jobs'] ?> cu reîncercări</p><?php } ?></section>
<section class="fm-panel" id="fm-integrations"><h2>Integrări externe</h2><p>Valorile sunt criptate în storage privat și nu se exportă cu setările. Câmpul gol păstrează valoarea salvată. Variabilele de mediu au prioritate; eliminarea unei valori locale nu șterge variabila serverului. Configurează Redis/Memcached din magazinul principal, deoarece conexiunea este comună instalării.</p><?php foreach(isset($data['integrations'])?$data['integrations']:array() as $name=>$service){ ?><div class="fm-row"><label for="fm-service-<?= $e($name) ?>"><?= $e($service['label']) ?><br><small><?= $service['configured']?'Configurat · '.$e($service['source']):'Neconfigurat' ?></small></label><div><input type="password" id="fm-service-<?= $e($name) ?>" name="services[<?= $e($name) ?>]" value="" autocomplete="new-password"><label><input type="checkbox" style="width:auto" name="remove_services[]" value="<?= $e($name) ?>"> Șterge valoarea locală</label></div></div><?php } ?><div class="fm-actions"><button name="operation" value="integrations_save">Salvează integrările în seif</button><button class="secondary" name="operation" value="s3_upload">Încarcă următorul fișier generat în S3</button></div></section>
<section class="fm-panel" id="fm-scripts"><h2>Inventar JavaScript inline</h2><p>Inspectează o pagină publică. Copiază hash-ul unui script independent în lista de aprobare, apoi salvează setările de extragere. Hash-ul se schimbă când codul se schimbă. Dependențele se verifică în browser.</p><input name="script_url" value="/" aria-label="URL public pentru inventar"><button class="secondary" name="operation" value="scripts_inventory">Inspectează scripturile</button><?php if(!empty($data['script_inventory'])){ ?><table class="fm-table"><tr><th>Identificator de aprobare</th><th>Dimensiune / stare</th></tr><?php foreach($data['script_inventory'] as $script){?><tr><td style="overflow-wrap:anywhere">sha256:<?= $e($script['hash']) ?></td><td><?= (int)$script['bytes'] ?> bytes · <?= $script['blocked']?'Protejat / nesuportat':'Candidat; verifică dependențele' ?></td></tr><?php } ?></table><?php } ?></section>
<section class="fm-panel" id="fm-batch"><h2>Optimizare în lot și pre-minificare</h2><p>Salvează întâi setările WebP/AVIF și minificare. Coada folosește configurația salvată, păstrează originalele și continuă în loturi de maximum 10 fișiere, cu buget de 5 secunde pe pas. Fișierele excluse sau nesuportate sunt păstrate. Fișierele se scanează în ferestre de 1.000; coada admite maximum 10.000 de directoare în așteptare.</p><div class="fm-actions"><button class="secondary" name="operation" value="batch_images">Scanează toate imaginile</button><button class="secondary" name="operation" value="batch_minify">Pregătește CSS / JS</button><button name="operation" value="batch_run">Continuă procesarea</button><button class="secondary" name="operation" value="batch_cancel">Anulează coada</button></div><?php if(!empty($data['batch'])){ ?><table class="fm-table"><tbody><?php foreach(array('status'=>'Stare','kind'=>'Tip','scanned'=>'Intrări scanate','processed'=>'Fișiere procesate','generated'=>'Fișiere cu rezultat optimizat','skipped'=>'Păstrate','errors'=>'Erori','message'=>'Detalii') as $key=>$label){if(isset($data['batch'][$key])){?><tr><th><?= $e($label) ?></th><td><?= $e($data['batch'][$key]) ?></td></tr><?php }} ?></tbody></table><?php } ?></section>
<section class="fm-panel" id="fm-diagnostic-log"><h2>Istoric diagnostic</h2><p>Activează diagnosticul detaliat pentru a păstra ultimele 30 decizii. Poți limita antetele și logul la hash-ul unei sesiuni din X-SkyNova-Session. Nu se salvează cookies, tokenuri, URL-uri cu query sau corpuri de pagini în acest istoric.</p><?php if(!empty($data['diagnostic_log'])){?><table class="fm-table"><tr><th>Data</th><th>Decizie</th><th>Rută</th></tr><?php foreach($data['diagnostic_log'] as $entry){?><tr><td><?= $e($entry['at']) ?></td><td><?= $e($entry['report']['status']) ?></td><td style="overflow-wrap:anywhere"><?= $e($entry['report']['route']) ?></td></tr><?php }?></table><?php } ?></section>
<section class="fm-panel" id="fm-health"><h2>Diagnostic de mediu</h2><table class="fm-table"><tbody>
<?php foreach ($data['health'] as $label=>$value) { ?><tr><th><?= $e($label) ?></th><td><?= $e($value) ?></td></tr><?php } ?>
</tbody></table><p>Testează HIT / MISS în antetele paginii, în aceeași sesiune. Analiza PageSpeed trimite către Google URL-ul public al magazinului. Poate dura până la 55 de secunde; cotele API se aplică.</p><div class="fm-actions"><select name="strategy" aria-label="Dispozitiv PageSpeed" style="max-width:180px"><option value="mobile">Mobil</option><option value="desktop">Desktop</option></select><button class="secondary" name="operation" value="pagespeed">Analizează cu Google</button><a class="fm-button" href="<?= $e($data['pagespeed']) ?>" target="_blank" rel="noopener noreferrer">Deschide PageSpeed Insights</a></div>
<?php if (!empty($data['report'])) { $report=$data['report']; ?><div class="fm-note"><strong>Scor măsurat: <?= $e($report['score']) ?>/100</strong> • <?= $e($report['strategy']) ?> • <?= $e($report['measured_at']) ?><ul><?php foreach ($report['metrics'] as $metric=>$value) { ?><li><?= $e($metric) ?>: <?= $e($value) ?></li><?php } ?></ul></div><?php if(!empty($report['recommendations'])){ ?><h3>Recomandări din măsurătoare</h3><p>Estimările aparțin raportului Lighthouse; nu se adună pentru a estima viteza finală. Verifică schimbările pe staging înainte de activare.</p><table class="fm-table"><tr><th>Audit și acțiune</th><th>Economie estimată</th></tr><?php foreach($report['recommendations'] as $recommendation){ ?><tr><td><a href="#fm-section-<?= $e($recommendation['section']) ?>"><?= $e($recommendation['title']) ?></a><br><?= $e($recommendation['action']) ?><br><small><?= $e($recommendation['audit']) ?></small></td><td><?= (int)$recommendation['savings_ms'] ?> ms / <?= (int)round($recommendation['savings_bytes']/1024) ?> KB</td></tr><?php } ?></table><?php } } ?></section>
<section class="fm-panel" id="fm-indexes"><h2>Indexuri bază de date</h2><p>Diagnosticul propune indexuri pentru schema existentă. Verifică utilitatea pe staging înainte de aplicare: adăugarea poate bloca temporar tabela și ocupă spațiu. Indexurile existente sunt păstrate; cele adăugate rămân după dezinstalarea modulului.</p><button class="secondary" name="operation" value="indexes_scan">Analizează indexurile</button>
<?php if(!empty($data['indexes'])){ ?><div style="overflow-x:auto"><table class="fm-table"><tr><th>Selectare</th><th>Tabel / coloane</th><th>Stare</th></tr><?php foreach($data['indexes'] as $id=>$row){ ?><tr><td><?php if(!$row['covered'] && !$row['conflict']){ ?><input style="width:auto" type="checkbox" name="index_ids[]" value="<?= $e($id) ?>" aria-label="<?= $e($row['table'].' '.implode(', ',$row['columns'])) ?>"><?php } ?></td><td><?= $e($row['table']) ?><br><?= $e(implode(', ',$row['columns'])) ?></td><td><?= $row['covered']?'Acoperit':($row['conflict']?'Conflict nume':'Propus') ?></td></tr><?php } ?></table></div><button name="operation" value="indexes_apply">Adaugă indexurile selectate (maximum 5)</button><?php } ?></section>
<section class="fm-panel" id="fm-inventory"><h2>Module și inventar cache</h2><p>Șabloanele sunt dezactivate până le verifici. Instanțele folosesc module_id sau layout_id din argumentele native. Golirea afectează intrările cu tagul exact.</p><button name="operation" value="module_presets">Încarcă șabloane pentru modulele standard</button><?php $moduleRows=ModuleRules::parse($s['module_rules']);if($moduleRows){?><div style="overflow:auto"><table class="fm-table"><tr><th>Rută modul</th><th>Activ</th><th>TTL secunde</th></tr><?php foreach($moduleRows as $route=>$rule){?><tr><td><?= $e($route) ?></td><td><select name="module_controls[<?= $e($route) ?>][enabled]"><option value="0" <?= isset($rule['enabled'])&&!$rule['enabled']?'selected':'' ?>>Oprit</option><option value="1" <?= !isset($rule['enabled'])||$rule['enabled']?'selected':'' ?>>Activ</option></select></td><td><input type="number" min="5" max="86400" name="module_controls[<?= $e($route) ?>][ttl]" value="<?= isset($rule['ttl'])?(int)$rule['ttl']:(int)$s['component_ttl'] ?>"></td></tr><?php }?></table></div><button name="operation" value="module_save">Salvează doar regulile modulelor</button><?php }?><input name="module_tag" placeholder="module:extension/module/featured:module:12"><button name="operation" value="purge_module">Golește modul / instanță</button><h3>Inventar privat · 200 intrări pe pagină</h3><?php $cachePage=isset($data['inventory_page'])?(int)$data['inventory_page']:0;?><p>Pagina <?= $cachePage+1 ?> · <a href="<?= $e(html_entity_decode($data['action'],ENT_QUOTES,'UTF-8').'&cache_page='.max(0,$cachePage-1)) ?>#fm-inventory">Anterior</a> · <a href="<?= $e(html_entity_decode($data['action'],ENT_QUOTES,'UTF-8').'&cache_page='.min(100,$cachePage+1)) ?>#fm-inventory">Următor</a></p><div style="overflow:auto"><table class="fm-table"><tr><th>ID fișier / taguri</th><th>Dimensiune</th><th>Expirare</th><th>Acțiune</th></tr><?php foreach(isset($data['inventory'])?$data['inventory']:array() as $row){$date=new \DateTime('@'.$row['expires']);$date->setTimezone(new \DateTimeZone($s['timezone']));?><tr><td style="overflow-wrap:anywhere"><?= $e($row['id'].'.cache') ?><br><?= $e(implode(', ',$row['tags'])) ?></td><td><?= (int)$row['bytes'] ?> bytes</td><td><?= $e($date->format('Y-m-d H:i:s T')) ?> · <?= $row['active']?'Activ':'Expirat' ?></td><td><button type="button" onclick="this.form.elements.entry_id.value=this.dataset.id;this.form.elements.inventory_submit.click()" data-id="<?= $e($row['id']) ?>">Golește</button></td></tr><?php }?></table></div><input type="hidden" name="entry_id"><button hidden name="operation" value="remove_entry" id="inventory_submit">Golește intrarea</button><button name="operation" value="browser_apply">Aplică profilul Apache cu backup</button><button name="operation" value="browser_profile">Exportă profil browser cache Apache/Nginx</button></section>
<section class="fm-panel" id="fm-maintenance"><h3>Invalidare selectivă</h3><input name="purge_tag" placeholder="product:40 / category:20 / route:common/home"><button name="operation" value="purge_tag">Golește tagul</button><h3>Cloudflare</h3><p>Cheia și zona se configurează în Integrări externe sau în mediul serverului. Doar URL-urile magazinului ales sunt acceptate.</p><textarea name="purge_urls" placeholder="https://magazin.ro/produs"></textarea><button name="operation" value="cloudflare">Invalidează URL-uri în Cloudflare</button><h2>Mentenanță recuperabilă</h2><p>Arhivează maximum 500 fișiere generate pe categorie în storage/skynova-maintenance. Originalele, seiful, sesiunile și sursele nu sunt mutate. După OCMOD refă modificările cu Refresh din meniul nativ OpenCart.</p><div class="fm-actions"><button name="operation" value="archive_images">Golește cache imagini</button><button name="operation" value="archive_logs">Arhivează loguri</button><button name="operation" value="archive_ocmod">Golește OCMOD compilat</button><button name="operation" value="archive_native">Golește cache nativ</button><button name="operation" value="archive_all">Toate categoriile generate</button></div><p>Salvarea setărilor invalidează paginile și rezultatele memorate. Purjarea nu șterge imagini originale sau cache-urile altor module.</p><div class="fm-actions"><button name="operation" value="save">Salvează configurația</button><button class="secondary" name="operation" value="purge">Golește cache-ul privat</button><button class="secondary" name="operation" value="gc">Curăță intrările expirate</button><button class="secondary" name="operation" value="export">Exportă configurația</button><button class="secondary" name="operation" value="runner">Exportă configurația CRON / loturi</button></div><label for="fm-import">Import JSON (opțional; verificat înainte de salvare)</label><textarea id="fm-import" name="import_json" placeholder="Lipește configurația exportată"></textarea><div class="fm-actions"><button class="secondary" name="operation" value="import">Importă în mod observare</button></div></section>
<?php if(!empty($data['daily'])){ ?><section class="fm-panel"><h2>Ultimele 30 de zile · toate magazinele</h2><table class="fm-table"><tr><th>Data</th><th>HIT</th><th>MISS</th><th>Bypass</th></tr><?php foreach($data['daily'] as $day=>$row){?><tr><td><?= $e($day) ?></td><td><?= (int)(isset($row['hit'])?$row['hit']:0) ?></td><td><?= (int)(isset($row['miss'])?$row['miss']:0) ?></td><td><?= (int)(isset($row['bypass'])?$row['bypass']:0) ?></td></tr><?php } ?></table></section><?php } ?>
<?php if(!empty($data['history'])){ ?><section class="fm-panel"><h2>Istoric PageSpeed · magazinul selectat</h2><table class="fm-table"><tr><th>Data</th><th>Dispozitiv</th><th>Scor</th></tr><?php foreach($data['history'] as $row){?><tr><td><?= $e($row['at']) ?></td><td><?= $e($row['report']['strategy']) ?></td><td><?= (int)$row['report']['score'] ?>/100</td></tr><?php } ?></table></section><?php } ?>
<div class="fm-footer">SkyNova Cache Suite • Nicio promisiune de scor sau creștere comercială. Rezultatele se măsoară pe magazinul real.</div>
</div></div></form></main></div>
<?php return ob_get_clean();
    }
}
