<?php
namespace FurMedia\Cache;
/** Admin-only controls. All mutations use the existing session nonce and permissions. */
class Adminnav {
 public static function render($url,$quick,$nonce,$modify) {
  $url=html_entity_decode($url,ENT_QUOTES,'UTF-8');
  $e=function($v){return htmlspecialchars($v,ENT_QUOTES,'UTF-8');};
  $actions=array('purge'=>'Tot cache-ul SkyNova','purge_pages'=>'Pagini și date catalog','purge_sql'=>'Rezultate SQL','purge_components'=>'Componente','purge_resources'=>'CSS / JS dinamice','gc'=>'Intrări expirate','archive_native'=>'Cache nativ OpenCart (arhivare)','archive_images'=>'Imagini generate (arhivare)');
  ob_start(); ?>
<li id="skynova-admin-nav" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bolt"></i> SkyNova Cache <span class="caret"></span></a><div class="dropdown-menu dropdown-menu-right dropdown-menu-end" style="width:320px;padding:14px;max-height:80vh;overflow:auto"><a href="<?= $e($url) ?>">Deschide SkyNova Cache Suite</a><p id="skynova-nav-status" role="status" aria-live="polite">Deschide meniul pentru starea cache-ului.</p><button type="button" class="btn btn-default btn-sm" data-skynova="status">Actualizează starea</button><hr><strong>Golire cache</strong><?php foreach($actions as $op=>$label){ ?><button type="button" class="btn btn-default btn-sm" style="display:block;width:100%;text-align:left;margin-top:5px" data-skynova="<?= $e($op) ?>" <?= $modify?'':'disabled' ?>><?= $e($label) ?></button><?php } ?><hr><button type="button" class="btn btn-primary btn-sm" data-skynova="warm_run" <?= $modify?'':'disabled' ?>>Preîncălzește acum · un lot</button><button type="button" class="btn btn-default btn-sm" data-skynova="warm_pause" <?= $modify?'':'disabled' ?>>Pauză</button><button type="button" class="btn btn-default btn-sm" data-skynova="warm_resume" <?= $modify?'':'disabled' ?>>Reia</button><p style="margin-top:8px">Imaginile și cache-ul nativ sunt arhivate recuperabil, maximum 500 fișiere/pas. Preîncălzirea verifică URL-uri publice; partajarea se aplică numai rutelor și sesiunilor aprobate.</p></div></li>
<?php $html=ob_get_clean();
  $config=json_encode(array('html'=>$html,'url'=>html_entity_decode($quick,ENT_QUOTES,'UTF-8'),'nonce'=>$nonce),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);
  return '<script>(function(c){function init(){var bar=document.querySelector("#header .navbar-right"),old=document.getElementById("skynova-admin-nav");if(!bar||old)return;bar.insertAdjacentHTML("afterbegin",c.html);var root=document.getElementById("skynova-admin-nav"),status=document.getElementById("skynova-nav-status"),busy=false;function run(op){if(busy)return;busy=true;status.textContent="Se procesează…";root.querySelectorAll("button[data-skynova]").forEach(function(b){b.disabled=true;});var body=new URLSearchParams();body.set("operation",op);body.set("fm_nonce",c.nonce);fetch(c.url,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:body.toString()}).then(function(r){return r.json();}).then(function(r){if(!r.ok)throw new Error(r.error||"Operațiune refuzată");status.textContent=r.message+" · "+r.state;}).catch(function(e){status.textContent=e.message||"Autentifică-te din nou.";}).finally(function(){busy=false;root.querySelectorAll("button[data-skynova]").forEach(function(b){b.disabled=!c.modify&&b.dataset.skynova!=="status";});});}root.addEventListener("click",function(e){var b=e.target.closest("[data-skynova]");if(b){e.preventDefault();e.stopPropagation();run(b.dataset.skynova);}});root.querySelector("a").addEventListener("click",function(){run("status");});}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})('.substr($config,0,-1).',"modify":'.($modify?'true':'false').'});</script>';
 }
}
