<?php
namespace FurMedia\Cache;
/** Approved resource transforms; never global DOM replacements or executable selectors. */
class Advanced {
 public static function url($url){if(!is_string($url)||$url===''){throw new \InvalidArgumentException('Invalid resource URL');}Delivery::urls(preg_match('~^(?:https://|/)~',$url)?$url:'/'.$url);}
 public static function rows($text){if(trim($text)===''){return array();}$rows=json_decode($text,true);if(!is_array($rows)||count($rows)>100){throw new \InvalidArgumentException('Advanced rules require JSON, maximum 100 entries');}return $rows;}
 public static function validate(array $s){
  if(!in_array($s['custom_position'],array('top','bottom'),true)||preg_match('~</|[<>]~',$s['custom_css'])||stripos($s['custom_js'],'</script')!==false){throw new \InvalidArgumentException('Invalid custom CSS/JS or position');}
  foreach(Settings::lines($s['lazy_blocks']) as $id){if(!preg_match('/^[a-z][a-z0-9_-]{0,63}$/iD',$id)){throw new \InvalidArgumentException('Lazy blocks require exact HTML IDs');}}
  foreach(self::rows($s['replacements']) as $row){if(!is_array($row)||!isset($row['find'],$row['replace'])||!is_string($row['find'])||!is_string($row['replace'])||$row['find']===''||strlen($row['find'])>512||strlen($row['replace'])>4096||preg_match('/token|nonce|csrf|session|password/i',$row['find'].$row['replace'])){throw new \InvalidArgumentException('Invalid replacement');}foreach(array('route','url') as $scope){if(isset($row[$scope])&&!is_string($row[$scope])){throw new \InvalidArgumentException('Invalid replacement scope');}}if(isset($row['route'])&&!preg_match('~^[a-z0-9_/]+$~D',$row['route'])){throw new \InvalidArgumentException('Invalid replacement route');}if(isset($row['url'])){self::url($row['url']);}if(isset($row['type'])&&!in_array($row['type'],array('html','css','js'),true)){throw new \InvalidArgumentException('Invalid replacement type');}if(isset($row['type'])&&$row['type']!=='html'&&preg_match('/[<>]/',$row['find'].$row['replace'])){throw new \InvalidArgumentException('CSS/JS replacements cannot contain HTML delimiters');}}
  foreach(self::rows($s['resource_attributes']) as $url=>$attrs){self::url($url);if(!is_array($attrs)){throw new \InvalidArgumentException('Invalid resource attributes');}foreach($attrs as $key=>$value){if(!in_array($key,array('media','fetchpriority','referrerpolicy','crossorigin','defer','async'),true)||!is_scalar($value)||strlen((string)$value)>128||preg_match('/[<>"\x27\r\n]/',(string)$value)){throw new \InvalidArgumentException('Unsupported resource attribute');}}}
  foreach(self::rows($s['delay_rules']) as $url=>$row){self::url($url);if(!is_array($row)||!isset($row['event'],$row['ms'])||!in_array($row['event'],array('pointerdown','keydown','scroll','load'),true)||!is_numeric($row['ms'])||$row['ms']<0||$row['ms']>30000){throw new \InvalidArgumentException('Delay requires approved URL, event and 0–30000 ms');}}
  foreach(self::rows($s['external_assets']) as $url=>$file){self::url($url);if(!is_string($file)||!preg_match('~^/?image/cache/furmedia_cache/[a-f0-9]{64}\.(css|js)$~D',$file)){throw new \InvalidArgumentException('Invalid imported asset mapping');}}
 }
 public static function replace($body,array $s,$type,$url=null){foreach(self::rows($s['replacements']) as $row){if((isset($row['type'])?$row['type']:'html')===$type&&(!isset($row['url'])||$row['url']===$url)){$body=str_replace($row['find'],$row['replace'],$body);}}return $body;}
 public static function transform($html,array $s,$assets=null,$route=''){ $rules=self::rows($s['replacements']);$rules=array_values(array_filter($rules,function($r)use($route){return !isset($r['route'])||$r['route']===$route;}));$s['replacements']=json_encode($rules);$parts=preg_split('~(<(?:pre|textarea|script|style)\b[^>]*>.*?</(?:pre|textarea|script|style)\s*>|<!--[\s\S]*?-->)~is',$html,-1,PREG_SPLIT_DELIM_CAPTURE);foreach($parts as $i=>$part){if($i%2===0){$parts[$i]=self::replace($part,$s,'html');}}$html=implode('',$parts);$maps=self::rows($s['external_assets']);$attrs=self::rows($s['resource_attributes']);$delays=self::rows($s['delay_rules']);$jobs=array();$canDelay=preg_match('~</'.($s['custom_position']==='top'?'head':'body').'\s*>~i',$html);
  $html=preg_replace_callback('~<(pre|textarea|style)\b[^>]*>.*?</\1\s*>|<!--[\s\S]*?-->|<script\b[^>]*>.*?</script\s*>|<link\b[^>]*>~is',function($m)use($maps,$attrs,$delays,$canDelay,$assets,$s,&$jobs){$tag=$m[0];if(!preg_match('/^<(script|link)\b/i',$tag,$kind)||preg_match('/\b(?:integrity|nonce|onload|onerror)\s*=/i',$tag)){return $tag;}if(!preg_match('~\s(src|href)\s*=\s*([\x22\x27])(.*?)\2~is',$tag,$src)){return $tag;}$url=html_entity_decode($src[3],ENT_QUOTES,'UTF-8');$local=$assets?$assets->local(isset($maps[$url])?$maps[$url]:$url):false;$delaySafe=$local&&filesize($local)<=2097152&&!Scripts::unsafe(file_get_contents($local));if($canDelay&&$delaySafe&&!isset($attrs[$url])&&isset($delays[$url])&&$kind[1]==='script'&&!preg_match('/\b(?:async|defer|type)\s*=|document\.write|currentScript/i',$tag)&&trim(substr($tag,strpos($tag,'>')+1,strrpos($tag,'</')-strpos($tag,'>')-1))===''){$job=$delays[$url];$job['url']=isset($maps[$url])?$maps[$url]:$url;$jobs[]=$job;return '<!-- SkyNova approved delayed script -->';}$newUrl=isset($maps[$url])?$maps[$url]:$url;if($assets){$newUrl=$assets->advancedResource($newUrl,$kind[1]==='script'?'js':'css',$s,$url);}if($newUrl!==$url){$value=htmlspecialchars($newUrl,ENT_QUOTES,'UTF-8');$tag=str_replace($src[0],' '.$src[1].'="'.$value.'"',$tag);}foreach(isset($attrs[$url])?$attrs[$url]:array() as $key=>$value){if(preg_match('/\s'.preg_quote($key,'/').'\b/i',$tag)){continue;}if(in_array($key,array('async','defer'),true)&&!in_array((string)$value,array('1','true'),true)){continue;}$value=htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$tag=preg_replace_callback('/>/',function($m)use($key,$value){return ' '.$key.'="'.$value.'">';},$tag,1);}return $tag;},$html);
  if($s['lazy_media']){$html=preg_replace_callback('~<(?:pre|textarea|script|style)\b[^>]*>.*?</(?:pre|textarea|script|style)\s*>|<!--[\s\S]*?-->|<(video|audio)\b[^>]*>.*?</\1\s*>~is',function($m){if(!preg_match('/^<(?:video|audio)\b/i',$m[0])){return $m[0];}if(preg_match('/\bautoplay\b/i',$m[0])){return $m[0];}$tag=preg_replace('/\spreload\s*=\s*([\x22\x27]).*?\1/i','',$m[0],1);return preg_replace('/>/', ' preload="none">',$tag,1);},$html);}
  $blocks=Settings::lines($s['lazy_blocks']);if($blocks){$html=preg_replace_callback('~<(?:pre|textarea|script|style)\b[^>]*>.*?</(?:pre|textarea|script|style)\s*>|<!--[\s\S]*?-->|<(div|section)\b[^>]*>~is',function($m)use($blocks){if(!preg_match('/^<(?:div|section)\b/i',$m[0])){return $m[0];}if(!preg_match('~\sid\s*=\s*([\x22\x27])(.*?)\1~i',$m[0],$id)||!in_array($id[2],$blocks,true)||preg_match('/\sstyle\s*=/i',$m[0])){return $m[0];}return substr($m[0],0,-1).' style="content-visibility:auto;contain-intrinsic-size:auto 500px">';},$html);}
  $script='';if($jobs){$script='<script>(function(){var jobs='.json_encode($jobs,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT).',done={};function run(i){if(done[i])return;done[i]=true;var x=document.createElement("script");x.src=jobs[i].url;x.async=false;document.body.appendChild(x)}jobs.forEach(function(j,i){window.addEventListener(j.event,function(){run(i)},{once:true,passive:true});setTimeout(function(){run(i)},j.ms)})})();</script>';}
  if($s['custom_css']){$html=preg_replace_callback('~</head\s*>~i',function($m)use($s){return '<style>'.self::replace($s['custom_css'],$s,'css').'</style>'.$m[0];},$html,1);}
  if($s['custom_js']){$script.='<script>'.self::replace($s['custom_js'],$s,'js').'</script>';}$end=$s['custom_position']==='top'?'head':'body';return preg_replace_callback('~</'.$end.'\s*>~i',function($m)use($script){return $script.$m[0];},$html,1);
 }
}
