<?php
namespace FurMedia\Cache;
class AdvancedAdmin {
 public static function render(array $d){$e=array('FurMedia\\Cache\\Admin','e');ob_start();?>
<section class="fm-panel" id="fm-database-tools"><h2>Mentenanță DB și EXPLAIN</h2><p>Maximum cinci tabele/operație. OPTIMIZE și conversia pot bloca accesul. Conversia MyISAM → InnoDB și curățarea creează backup privat JSON: maximum 10.000 rânduri / 16 MB. Pentru tabele mai mari folosește mentenanță cu dump extern.</p><button class="secondary" name="operation" value="db_inspect">Inspectează tabelele</button>
<?php if(!empty($d['db_tables'])){?><div style="overflow:auto"><table class="fm-table"><tr><th>Selectează</th><th>Tabel / motor</th><th>Rânduri estimate</th><th>MB / liber MB</th></tr><?php foreach($d['db_tables'] as $name=>$row){?><tr><td><input type="checkbox" style="width:auto" name="db_tables[]" value="<?= $e($name) ?>"></td><td><?= $e($name) ?> / <?= $e($row['engine']) ?></td><td><?= (int)$row['rows'] ?></td><td><?= round($row['bytes']/1048576,2) ?> / <?= round($row['free']/1048576,2) ?></td></tr><?php } ?></table></div><?php } ?>
<div class="fm-actions"><button class="secondary" name="operation" value="db_analyze">ANALYZE selecția</button><button class="secondary" name="operation" value="db_optimize">OPTIMIZE selecția</button><button class="secondary" name="operation" value="db_convert">Backup și conversie InnoDB</button></div><label><input style="width:auto" type="checkbox" name="db_confirm" value="1"> Confirm conversia sau ștergerea după verificare</label>
<div class="fm-row"><label for="fm-explain">SELECT de catalog pentru EXPLAIN</label><textarea id="fm-explain" name="explain_sql" spellcheck="false"></textarea></div><button class="secondary" name="operation" value="db_explain">EXPLAIN fără executarea SELECT-ului</button>
<div class="fm-row"><label>Curățare date vechi</label><div><select name="retention_kind"><option value="activity">Activitate clienți</option><option value="search">Istoric căutări</option><option value="cart">Coșuri anonime</option><option value="session">Sesiuni expirate</option></select><input name="retention_days" type="number" min="30" max="3650" value="90" aria-label="Zile de păstrat"></div></div><div class="fm-actions"><button class="secondary" name="operation" value="db_preview">Previzualizează curățarea</button><button class="secondary" name="operation" value="db_retention">Backup și ștergere după previzualizare</button></div>
<?php if(!empty($d['db_result'])){?><pre style="white-space:pre-wrap;overflow-wrap:anywhere"><?= $e(json_encode($d['db_result'],JSON_PRETTY_PRINT)) ?></pre><?php } ?><h3>SELECT-uri lente recente</h3><p>Maximum 30 mostre anonimizate; formele de mai jos nu sunt SQL gata de executat.</p><?php foreach(isset($d['sql_profile'])?$d['sql_profile']:array() as $sample){?><p style="overflow-wrap:anywhere"><code><?= $e(json_encode($sample)) ?></code></p><?php } ?></section>
<section class="fm-panel" id="fm-external-import"><h2>Import resurse externe</h2><p>HTTPS public, maximum 2 MB, fără redirecturi. SHA256 trebuie să corespundă fișierului verificat. CSS cu @import este refuzat; imaginile și fonturile referite rămân la origine. Importul salvează maparea și invalidează cache-ul.</p><input name="asset_url" aria-label="URL HTTPS resursă" placeholder="https://cdn.example/script.js"><input name="asset_hash" aria-label="SHA256 așteptat" placeholder="SHA256"><select name="asset_type"><option value="js">JavaScript</option><option value="css">CSS</option></select><button class="secondary" name="operation" value="external_import">Importă resursa verificată</button></section>
<?php return ob_get_clean(); }
}
