<?php
namespace FurMedia\Cache;
/** Bounded, selected DB maintenance. Backups precede conversion or retention deletes. */
class Dbtools {
 private $db;private $prefix;private $root;
 public function __construct($db,$prefix,$root){if(!preg_match('/^[a-zA-Z0-9_]+$/D',$prefix)){throw new \InvalidArgumentException('Invalid prefix');}$this->db=$db;$this->prefix=$prefix;$this->root=rtrim($root,'/\\');if(!is_dir($root)&&!mkdir($root,0700,true)){throw new \RuntimeException('DB backup unavailable');}}
 public function tables(){ $rows=$this->db->query('SHOW TABLE STATUS')->rows;$out=array();foreach($rows as $row){if(preg_match('/^skynova_(?:bak|restore|meta|prev|replaced|ngram)_[a-f0-9]{32}$/D',$row['Name'])||strpos($row['Name'],$this->prefix)!==0||!preg_match('/^[a-zA-Z0-9_]+$/D',$row['Name'])){continue;}$out[$row['Name']]=array('engine'=>$row['Engine'],'rows'=>(int)$row['Rows'],'bytes'=>(int)$row['Data_length']+(int)$row['Index_length'],'free'=>(int)$row['Data_free']);}return $out;}
 private function selected(array $ids){$tables=$this->tables();if(count($ids)>5){throw new \InvalidArgumentException('Maximum five tables per operation');}foreach($ids as $id){if(!is_string($id)||!isset($tables[$id])){throw new \InvalidArgumentException('Unknown native table');}}return $tables;}
 public function maintain($operation,array $ids){if(!in_array($operation,array('ANALYZE','OPTIMIZE'),true)){throw new \InvalidArgumentException('Invalid DB operation');}$this->selected($ids);$out=array();foreach(array_unique($ids) as $id){$out[$id]=$this->db->query($operation.' TABLE `'.$id.'`')->rows;}return $out;}
 public function scheduled(array $ids,$root){
  $schedule=new FileStore($root);$lock=$schedule->lease('db:analyze');if(!$lock){return array('busy'=>true);}
  try{if($schedule->get('db:analyze:last')!==null){return array('skipped'=>true);}if(!$ids){return array('skipped'=>true);}$result=$this->maintain('ANALYZE',$ids);if(!$schedule->set('db:analyze:last',true,86400)){throw new \RuntimeException('Cannot persist DB schedule');}return $result;}
  finally{flock($lock,LOCK_UN);fclose($lock);}
 }
 public function explain($sql){if(!self::safeSelect($sql,$this->prefix)){throw new \InvalidArgumentException('Use a single read-only catalog SELECT without functions, comments or side effects');}return $this->db->query('EXPLAIN '.$sql)->rows;}
 public static function safeSelect($sql,$prefix){if(!is_string($sql)){return false;}$masked=Sqlprofile::shape($sql);if($masked==='[unparsed SELECT]'){return false;}$from=preg_split('/\b(?:WHERE|GROUP|ORDER|LIMIT|HAVING)\b/i',preg_replace('/^.*?\bFROM\b/is','',$masked),2);if(strpos($from[0],',')!==false||preg_match('/\b(?:FROM|JOIN|STRAIGHT_JOIN)\s+`?[a-z0-9_]+`?\s*\./i',$masked)){return false;}if(!is_string($sql)||strlen($sql)>8192||!preg_match('/^SELECT\s/i',$sql)||preg_match('/[;#@\\\\]|--|\/\*|\b(?:UNION|INTO|OUTFILE|DUMPFILE|FOR|LOCK|SLEEP|BENCHMARK|PROCEDURE|WITH)\b/i',$sql)){return false;}if(preg_match('/\b[a-z_][a-z0-9_]*\s*\(/i',$sql)){return false;}if(!preg_match_all('/\b(?:FROM|JOIN|STRAIGHT_JOIN)\s+`?([a-zA-Z0-9_]+)`?/i',$sql,$m)){return false;}$allowed=array('product','product_description','product_to_store','product_to_category','category','category_description','category_path','manufacturer','information','seo_url','url_alias');foreach($m[1] as $table){if(!in_array($table,array_map(function($t)use($prefix){return $prefix.$t;},$allowed),true)){return false;}}return !preg_match('/\bSELECT\b/i',substr($sql,6));}
 private function backup($table,$where='1'){
  $count=(int)$this->db->query('SELECT COUNT(*) AS total FROM `'.$table.'` WHERE '.$where)->row['total'];if($count>10000){throw new \RuntimeException('Backup exceeds 10000 rows; use an external database dump for this table');}$create=$this->db->query('SHOW CREATE TABLE `'.$table.'`')->row;$rows=$this->db->query('SELECT * FROM `'.$table.'` WHERE '.$where.' LIMIT 10001')->rows;if(count($rows)>10000){throw new \RuntimeException('Concurrent growth exceeds backup bound');}$file=$this->root.'/'.gmdate('Ymd-His').'-'.bin2hex(Entropy::bytes(6)).'.json';$json=json_encode(array('table'=>$table,'where'=>$where,'create'=>$create,'rows'=>$rows));if($json===false||strlen($json)>16777216||file_put_contents($file,$json,LOCK_EX)!==strlen($json)){throw new \RuntimeException('Bounded private backup failed');}@chmod($file,0600);return basename($file);
 }
 public function convert(array $ids){$tables=$this->selected($ids);$out=array();foreach($ids as $id){if($tables[$id]['engine']!=='MyISAM'){throw new \InvalidArgumentException('Only MyISAM to InnoDB conversion is supported');}}foreach($ids as $id){$this->db->query('LOCK TABLES `'.$id.'` WRITE');try{$backup=$this->backup($id);$this->db->query('ALTER TABLE `'.$id.'` ENGINE=InnoDB');}finally{$this->db->query('UNLOCK TABLES');}$out[$id]=array('backup'=>$backup,'engine'=>'InnoDB');}return $out;}
 public function retention($kind,$days,$apply=false){if(!is_string($kind)||!is_scalar($days)){throw new \InvalidArgumentException('Invalid retention selection');}$days=max(30,min(3650,(int)$days));$map=array('activity'=>array('customer_activity','date_added'),'search'=>array('customer_search','date_added'),'cart'=>array('cart','date_added'),'session'=>array('session','expire'));if(!isset($map[$kind])){throw new \InvalidArgumentException('Unsupported retention kind');}list($name,$date)=$map[$kind];$table=$this->prefix.$name;$tables=$this->tables();if(!isset($tables[$table])){throw new \RuntimeException('Retention table unavailable');}$fields=$this->db->query('SHOW COLUMNS FROM `'.$table.'`')->rows;$found=false;foreach($fields as $field){if($field['Field']===$date){$found=true;}}if(!$found){throw new \RuntimeException('Retention date column unavailable');}$where='`'.$date.'` < DATE_SUB(NOW(), INTERVAL '.$days.' DAY)';if($kind==='cart'){$where.=' AND `customer_id` = 0';}$count=(int)$this->db->query('SELECT COUNT(*) AS total FROM `'.$table.'` WHERE '.$where)->row['total'];$result=array('kind'=>$kind,'days'=>$days,'eligible'=>$count,'applied'=>false);if($apply&&$count){$result['backup']=$this->backup($table,$where);$snapshot=json_decode(file_get_contents($this->root.'/'.$result['backup']),true);$primary=array('activity'=>'activity_id','search'=>'customer_search_id','cart'=>'cart_id','session'=>'session_id');$ids=array();foreach($snapshot['rows'] as $row){if(!isset($row[$primary[$kind]])||!is_scalar($row[$primary[$kind]])){throw new \RuntimeException('Retention primary key unavailable');}$ids[]="'".$this->db->escape((string)$row[$primary[$kind]])."'";}if($ids){$this->db->query('DELETE FROM `'.$table.'` WHERE '.$where.' AND `'.$primary[$kind].'` IN ('.implode(',',$ids).')');}$result['applied']=true;}return $result;}
}
