<?php
namespace FurMedia\Cache;
class Delivery {
 public static function urls($text){foreach(Settings::lines($text) as $url){if(strlen($url)>2048||!preg_match('#^(?:https://[a-z0-9.-]+(?::443)?/|/(?!/))[a-z0-9_./%?=&+~-]+$#iD',$url)||preg_match('/(?:token|session|nonce|\.\.)/i',rawurldecode($url))){throw new \InvalidArgumentException('Use public HTTPS or relative resource URLs');}}}
 public static function hints(array $s){$html='';foreach(Settings::lines($s['prefetch_urls']) as $url){$html.='<link rel="prefetch" href="'.htmlspecialchars($url,ENT_QUOTES,'UTF-8').'">';}foreach(Settings::lines($s['preload_urls']) as $line){$p=explode('|',$line,2);$html.='<link rel="preload" href="'.htmlspecialchars($p[0],ENT_QUOTES,'UTF-8').'" as="'.$p[1].'"'.($p[1]==='font'?' crossorigin':'').'>'; }return $html;}
 public static function profile(array $s){$types=array('images'=>array('image/jpeg','image/png','image/gif','image/webp','image/avif','image/svg+xml'),'css'=>array('text/css'),'js'=>array('text/javascript','application/javascript'),'video'=>array('video/mp4','video/webm'),'pdf'=>array('application/pdf'),'fonts'=>array('font/woff','font/woff2'));$apache="# SkyNova static policy: review and insert into store .htaccess\n<IfModule mod_expires.c>\n<FilesMatch \"\\.(jpe?g|png|gif|webp|avif|svg|css|js|mp4|webm|pdf|woff2?)$\">\nExpiresActive On\n";$nginx="# Alternative: integrate in existing nginx server, avoid duplicate locations\n";$ext=array('images'=>'jpe?g|png|gif|webp|avif|svg','css'=>'css','js'=>'js','video'=>'mp4|webm','pdf'=>'pdf','fonts'=>'woff2?');foreach($types as $kind=>$mimes){$ttl=(int)$s['browser_'.$kind];foreach($mimes as $mime){$apache.='ExpiresByType '.$mime.' "access plus '.$ttl.' seconds"'."\n";}$nginx.='location ~* \.('.$ext[$kind].')$ { try_files $uri =404; expires '.$ttl.'s; add_header Vary Accept-Encoding; }'."\n";}return $apache."</FilesMatch>\n</IfModule>\n\n".$nginx;}
 public static function applyApache($webRoot,$privateRoot,array $s){
  if(!is_dir($privateRoot)&&!mkdir($privateRoot,0700,true)){throw new \RuntimeException('Backup directory unavailable');}$root=realpath($webRoot);if(!$root||is_link($webRoot)||!Paths::privateStorage($privateRoot,$root)){throw new \RuntimeException('Private backup storage required');}$file=$root.'/.htaccess';if(is_link($file)){throw new \RuntimeException('Symlink configuration refused');}$original=is_file($file)?file_get_contents($file):'';if(strlen($original)>1048576){throw new \RuntimeException('Server configuration too large');}
  $begin='# SKYNOVA-BROWSER-START';$end='# SKYNOVA-BROWSER-END';$clean=preg_replace('~\n?# SKYNOVA-BROWSER-START.*?# SKYNOVA-BROWSER-END\n?~s',"\n",$original);$profile=explode("\n# Alternative:",self::profile($s))[0];$updated=rtrim($clean)."\n".$begin."\n".$profile."\n".$end."\n";
  if(!is_dir($privateRoot)&&!mkdir($privateRoot,0700,true)){throw new \RuntimeException('Backup directory unavailable');}$backup=$privateRoot.'/htaccess-'.gmdate('Ymd-His').'-'.bin2hex(Entropy::bytes(4)).'.txt';if(file_put_contents($backup,$original,LOCK_EX)!==strlen($original)){throw new \RuntimeException('Cannot back up server configuration');}@chmod($backup,0600);$temp=tempnam($root,'.skynova-');if(file_put_contents($temp,$updated,LOCK_EX)!==strlen($updated)||!rename($temp,$file)){if(is_file($temp)){unlink($temp);}throw new \RuntimeException('Cannot update server configuration');}return basename($backup);
 }
 public static function gzipAllowed($accept){foreach(explode(',',strtolower($accept)) as $part){$bits=explode(';',trim($part));if($bits[0]!=='gzip'){continue;}$q=1;foreach(array_slice($bits,1) as $param){if(preg_match('/^\s*q\s*=\s*([0-9.]+)\s*$/',$param,$m)){$q=(float)$m[1];}}return $q>0;}return false;}
 public static function compressed($body,$accept,FileStore $store,$ttl,$reserve){if(!self::gzipAllowed($accept)||!function_exists('gzencode')||ini_get('zlib.output_compression')){return null;}$key='gzip:'.hash('sha256',$body);$encoded=$reserve?$store->get($key):null;if(!is_string($encoded)){$gzip=gzencode($body,6);if($gzip===false){return null;}$encoded=base64_encode($gzip);if($reserve){$store->set($key,$encoded,$ttl,array('compression'));}}return base64_decode($encoded,true);}
}
