<?php
namespace FurMedia\Cache;
/** Optional worker owns only immutable hashed public generated assets. Never HTML/API. */
class Pwa {
    public static function names($text){$names=Settings::lines($text);if(count($names)>10){throw new \InvalidArgumentException('At most ten owned PWA cache names');}foreach($names as $name){if(!preg_match('/^[a-zA-Z0-9_.-]{1,80}$/D',$name)){throw new \InvalidArgumentException('Invalid owned PWA cache name');}}return $names;}
    public static function registration($url,$scope){return '<script>(function(){if(!window.isSecureContext||!("serviceWorker" in navigator))return;navigator.serviceWorker.getRegistrations().then(function(rs){var scope=new URL('.json_encode($scope).',location.href).href;if(rs.some(function(r){var w=r.active||r.waiting||r.installing;return (scope.indexOf(r.scope)===0||r.scope.indexOf(scope)===0)&&w&&w.scriptURL.indexOf("furmedia_cache")===-1}))return;return navigator.serviceWorker.register('.json_encode($url).',{scope:'.json_encode($scope).'}).then(function(r){return r.update()})}).catch(function(){})})();</script>';}
    public static function worker($scope,$epoch,$limit=100){$name='skynova-assets-'.substr(hash('sha256',$epoch),0,16);$prefix=rtrim($scope,'/').'/image/cache/furmedia_cache/';$limit=max(20,min(500,(int)$limit));
        return '"use strict";const NAME='.json_encode($name).',PREFIX='.json_encode($prefix).',LIMIT='.$limit.';self.addEventListener("install",e=>e.waitUntil(self.skipWaiting()));self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(ns=>Promise.all(ns.filter(n=>n.startsWith("skynova-assets-")&&n!==NAME).map(n=>caches.delete(n)))).then(()=>self.clients.claim())));self.addEventListener("fetch",e=>{const r=e.request,u=new URL(r.url);if(r.method!=="GET"||u.origin!==self.location.origin||u.search||!u.pathname.startsWith(PREFIX)||!/^([a-f0-9]{64})\.(css|js|webp|avif)$/.test(u.pathname.slice(PREFIX.length)))return;e.respondWith(caches.open(NAME).then(async c=>{const hit=await c.match(r);if(hit)return hit;const response=await fetch(r);if(response.status===200&&!response.redirected&&/public/.test(response.headers.get("cache-control")||"")&&/immutable/.test(response.headers.get("cache-control")||"")&&/^(text\/css|(?:text|application)\/javascript|image\/(?:webp|avif))\b/.test(response.headers.get("content-type")||"")){await c.put(r,response.clone());const keys=await c.keys();for(let i=0;i<keys.length-LIMIT;i++)await c.delete(keys[i]);}return response;}));});';
    }
    public static function controls($names){$allowed=self::names($names);return '<div id="skynova-pwa-local"><button type="button" class="secondary" id="skynova-pwa-inspect">Inspectează cache-ul acestui browser</button> <button type="button" class="secondary" id="skynova-pwa-clear">Șterge cache-urile declarate ale acestui browser</button><pre id="skynova-pwa-status" style="white-space:pre-wrap"></pre></div><script>(function(){const allowed='.json_encode($allowed).',status=document.getElementById("skynova-pwa-status");async function run(clear){if(!window.isSecureContext||!("caches" in window)){status.textContent="CacheStorage indisponibil pe această origine";return;}let out=[];for(const n of await caches.keys()){if(!n.startsWith("skynova-assets-")&&!allowed.includes(n))continue;const c=await caches.open(n),keys=await c.keys();out.push(n+": "+keys.length+" resurse"+(clear?" — șters":""));if(clear)await caches.delete(n);}status.textContent=out.join("\n")||"Niciun cache declarat";}document.getElementById("skynova-pwa-inspect").onclick=()=>run(false).catch(()=>{status.textContent="Inspecție indisponibilă";});document.getElementById("skynova-pwa-clear").onclick=()=>run(true).catch(()=>{status.textContent="Ștergere indisponibilă";});})();</script>';}
}
