<?php
namespace FurMedia\Cache;
/** Optional trigram candidate index; native LIKE remains the final truth. */
class SearchIndex {
    private $db;private $prefix;private $root;private $gate;private $jobs;private $archive;
    public function __construct($db,$prefix,$root,$archiveRoot,$maxMb=2048){if(!preg_match('/^[a-zA-Z0-9_]*$/D',$prefix)){throw new \InvalidArgumentException('Invalid search prefix');}$this->db=$db;$this->prefix=$prefix;$this->root=$root;$this->gate=new FileStore($root.'/gate');$this->jobs=new FileStore($root.'/job');$this->archive=new Dbarchive($db,$prefix,$archiveRoot,$maxMb);}
    public static function invalidate($root){$gate=new FileStore($root.'/gate');$before=$gate->generation();$gate->purge();if($gate->generation()===$before){throw new \RuntimeException('Cannot invalidate auxiliary search index before native mutation');}}
    public function generation(){return $this->gate->generation();}
    public function status(){return array('job'=>$this->jobs->get('state')?:array('phase'=>'idle'),'active'=>$this->gate->get('active'));}
    public function start(){if(!function_exists('mb_substr')){throw new \RuntimeException('mbstring required for Unicode search index');}$lock=$this->jobs->lease('search');if(!$lock){throw new \RuntimeException('Search build busy');}
        try{$old=$this->jobs->get('state');if($old&&in_array($old['phase'],array('snapshot','build','paused'),true)){throw new \RuntimeException('Finish or cancel the search build first');}$table=$this->prefix.'product_description';$fields=$this->db->query('SHOW FULL COLUMNS FROM `'.$table.'`')->rows;$collation=null;foreach($fields as $field){if($field['Field']==='name'){$collation=$field['Collation'];}}
            if(!is_string($collation)||!preg_match('/^(utf8mb4|utf8mb3|utf8|latin1)_(?:general_ci|unicode_ci|0900_ai_ci|bin)$/D',$collation,$match)){throw new \RuntimeException('This name collation requires native search; auxiliary index not enabled');}
            self::invalidate($this->root);$archive=$this->archive->start($table);$id=bin2hex(Entropy::bytes(16));$s=array('phase'=>'snapshot','id'=>$id,'archive'=>$archive['id'],'table'=>'skynova_ngram_'.$id,'generation'=>$this->gate->generation(),'collation'=>$collation,'charset'=>$match[1],'rows'=>0,'grams'=>0,'last'=>array(),'total'=>0);if(!$this->jobs->set('state',$s,31536000)){throw new \RuntimeException('Cannot persist search progress');}return $s;
        }finally{flock($lock,LOCK_UN);fclose($lock);}
    }
    public function pause($resume=false){$lock=$this->jobs->lease('search');if(!$lock){throw new \RuntimeException('Search build busy');}try{$s=$this->jobs->get('state');if(!$s){return array('phase'=>'idle');}if($resume&&$s['phase']==='paused'){$s['phase']=$s['resume'];}elseif(!$resume&&in_array($s['phase'],array('snapshot','build'),true)){$s['resume']=$s['phase'];$s['phase']='paused';}if(!$this->jobs->set('state',$s,31536000)){throw new \RuntimeException('Cannot persist search progress');}return $s;}finally{flock($lock,LOCK_UN);fclose($lock);}}
    public function step($limit=100){$lock=$this->jobs->lease('search');if(!$lock){return $this->status()['job'];}try{$s=$this->jobs->get('state');if(!$s){return array('phase'=>'idle');}
            if($s['phase']==='snapshot'){$a=$this->archive->state($s['archive']);if($a['phase']==='snapshot'){$this->archive->step($s['archive']);$a=$this->archive->state($s['archive']);}if($a['phase']!=='export'||$a['parts']){throw new \RuntimeException('Search snapshot unavailable');}$this->db->query('DROP TABLE IF EXISTS `'.$s['table'].'`');$s['total']=$a['total'];
                $this->db->query('CREATE TABLE `'.$s['table'].'` (gram VARCHAR(3) CHARACTER SET '.$s['charset'].' COLLATE '.$s['collation'].' NOT NULL, product_id INT NOT NULL, language_id INT NOT NULL, PRIMARY KEY(gram,product_id,language_id)) ENGINE=InnoDB');$s['phase']='build';if(!$this->jobs->set('state',$s,31536000)){throw new \RuntimeException('Cannot persist search progress');}
            }elseif($s['phase']==='build'){$a=$this->archive->state($s['archive']);$where=$s['last']?' WHERE (product_id,language_id) > ('.(int)$s['last'][0].','.(int)$s['last'][1].')':'';$rows=$this->db->query('SELECT product_id,language_id,name FROM `'.$a['snapshot'].'`'.$where.' ORDER BY product_id,language_id LIMIT '.max(1,min(250,(int)$limit)))->rows;
                $values=array();foreach($rows as $row){$grams=array();$length=mb_strlen($row['name'],'UTF-8');for($i=0;$i+3<=$length;$i++){$gram=mb_substr($row['name'],$i,3,'UTF-8');$grams[$gram]=true;}foreach($grams as $gram=>$unused){$values[]="('".$this->db->escape((string)$gram)."',".(int)$row['product_id'].','.(int)$row['language_id'].')';}$s['last']=array((int)$row['product_id'],(int)$row['language_id']);}
                foreach(array_chunk($values,1000) as $chunk){$this->db->query('INSERT IGNORE INTO `'.$s['table'].'` VALUES '.implode(',',$chunk));}$s['rows']+=count($rows);$s['grams']+=count($values);
                if($s['rows']===$s['total']){$s['phase']=$this->gate->set('active',array('table'=>$s['table'],'prefix'=>$this->prefix,'generation'=>$s['generation'],'rows'=>$s['rows'],'grams'=>$s['grams'],'collation'=>$s['collation']),31536000,array('search'),$s['generation'])?'ready':'stale';if(!$this->jobs->set('state',$s,31536000)){throw new \RuntimeException('Cannot persist completed search index');}$this->archive->discardSnapshot($s['archive']);}elseif(!$rows){throw new \RuntimeException('Search snapshot incomplete');}if(!$this->jobs->set('state',$s,31536000)){throw new \RuntimeException('Cannot persist search progress');}
            }return $s;
        }finally{flock($lock,LOCK_UN);fclose($lock);}
    }
    public function rewrite($sql){$active=$this->gate->get('active');if(!$active||$active['prefix']!==$this->prefix||$active['generation']!==$this->gate->generation()||!preg_match('/^skynova_ngram_[a-f0-9]{32}$/D',$active['table'])||!is_string($sql)||!preg_match('/^\s*SELECT\b/i',$sql)||preg_match('/[;#]|--|\/\*/',$sql)||preg_match_all('/\bSELECT\b/i',$sql)>1||!preg_match('/\b(?:FROM|JOIN)\s+`?'.preg_quote($this->prefix.'product_description','/').'`?\s+(?:AS\s+)?pd\b/i',$sql)){return $sql;}
        return preg_replace_callback("~\\bpd\\.name\\s+LIKE\\s+'([^'\\\\]*)'|'(?:\\\\.|''|[^'\\\\])*'|\"(?:\\\\.|[^\"\\\\])*\"|`[^`]*`~i",function($m)use($active){if(!isset($m[1])||$m[1]===''){return $m[0];}$pattern=$m[1];if(strlen($pattern)<3||$pattern[0]!=='%'||substr($pattern,-1)!=='%'){return $m[0];}$text=substr($pattern,1,-1);if(strpbrk($text,'%_')!==false||!mb_check_encoding($text,'UTF-8')||mb_strlen($text,'UTF-8')<3){return $m[0];}$grams=array_unique(array(mb_substr($text,0,3,'UTF-8'),mb_substr($text,-3,3,'UTF-8')));$conditions=array();foreach($grams as $gram){$conditions[]="pd.product_id IN (SELECT product_id FROM `".$active['table']."` WHERE gram = '".$this->db->escape($gram)."')";}return '('.$m[0].' AND '.implode(' AND ',$conditions).')';},$sql);
    }
}
