<?php
if(PHP_SAPI!=='cli'){exit(1);}
// Bounded public HTTP acceptance probe. Never creates an account, order or payment.
// Run only on TrinityConcept hosting; cookie jars contain this probe's new guest sessions.
$base='https://trinityconcept.ro/';$dir=__DIR__.'/probe-'.getmypid();mkdir($dir,0700);
$uas=array('android'=>'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36','iphone'=>'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1','desktop'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/130.0.0.0 Safari/537.36');
$rows=array();$checks=array();
function req($who,$path,$post=null,$ajax=false){global $base,$dir,$uas,$rows;$headers=array();$c=curl_init($base.$path);curl_setopt_array($c,array(CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>45,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_USERAGENT=>$uas[$who==='android2'?'android':$who],CURLOPT_COOKIEFILE=>$dir.'/'.$who.'.cookies',CURLOPT_COOKIEJAR=>$dir.'/'.$who.'.cookies',CURLOPT_ENCODING=>'',CURLOPT_HEADERFUNCTION=>function($c,$h)use(&$headers){$p=explode(':',$h,2);if(count($p)===2)$headers[strtolower(trim($p[0]))]=trim($p[1]);return strlen($h);}));if($post!==null){curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,http_build_query($post));}if($ajax)curl_setopt($c,CURLOPT_HTTPHEADER,array('X-Requested-With: XMLHttpRequest'));$body=curl_exec($c);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);$ms=round(curl_getinfo($c,CURLINFO_TOTAL_TIME)*1000);$error=curl_error($c);curl_close($c);$r=array('session'=>$who,'path'=>$path,'method'=>$post===null?'GET':'POST','status'=>$status,'cache'=>isset($headers['x-furmedia-cache'])?$headers['x-furmedia-cache']:'none','ms'=>$ms,'bytes'=>strlen((string)$body),'error'=>$error);$rows[]=$r;return array('row'=>$r,'body'=>(string)$body,'headers'=>$headers);}
function check($name,$ok){global $checks;$checks[]=array('name'=>$name,'passed'=>(bool)$ok);}
foreach(array('android','android2','iphone','desktop') as $who){$history=array();for($i=0;$i<4;$i++){$r=req($who,'index.php?route=common/home');$history[]=$r['row']['cache'];check($who.' home '.$i,$r['row']['status']===200&&strpos($r['body'],'Trinity')!==false&&strpos($r['body'],'Fatal error')===false);if($who==='android2'&&$i===0)check('fresh second Android reuses only shared shell',$r['row']['cache']==='HIT');}check($who.' repeated home HIT',in_array('HIT',$history,true));}
foreach(array('index.php?route=product/category&path=64','index.php?route=product/product&product_id=6624','index.php?route=product/category&path=64&sort=p.price&order=ASC','index.php?route=product/search&search=ametist') as $path){for($i=0;$i<3;$i++){$r=req('android',$path);check('public page renders '.$path.' '.$i,$r['row']['status']===200&&strpos($r['body'],'</html>')!==false&&strpos($r['body'],'Fatal error')===false);}}
$r=req('android','index.php?route=common/home',null,true);check('AJAX bypass',$r['row']['cache']==='BYPASS-private-request');
$r=req('android','index.php?route=common/home&probe_unknown=1');check('unknown query bypass',$r['row']['cache']==='BYPASS-query');
$r=req('android','index.php?route=checkout/cart');check('cart excluded',$r['row']['cache']==='BYPASS-sensitive-route');
$r=req('android','index.php?route=account/login');check('login excluded',$r['row']['cache']==='BYPASS-sensitive-route');
$add=req('android','index.php?route=checkout/cart/add',array('product_id'=>6624,'quantity'=>1));$json=json_decode($add['body'],true);$added=!empty($json['success']);check('guest test cart add succeeds',$added);
if($added){$cart=req('android','index.php?route=checkout/cart');check('cart remains native',$cart['row']['cache']==='BYPASS-private-customer'||$cart['row']['cache']==='BYPASS-sensitive-route');check('own cart contains chosen product',strpos($cart['body'],'6624')!==false);$home=req('android','index.php?route=common/home');check('nonempty cart home bypass',$home['row']['cache']==='BYPASS-private-customer');$other=req('android2','index.php?route=checkout/cart');check('second Android cart does not contain removal control',strpos($other['body'],'cart.remove(')===false);$checkout=req('android','index.php?route=checkout/checkout');check('checkout renders without order/payment',$checkout['row']['status']===200&&strpos($checkout['body'],'Fatal error')===false);if(preg_match('/cart\.remove\(\s*[\x27\x22]([^\x27\x22]+)[\x27\x22]/',$cart['body'],$m)){req('android','index.php?route=checkout/cart/remove',array('key'=>$m[1]));$empty=req('android','index.php?route=checkout/cart');check('test cart cleaned',strpos($empty['body'],'cart.remove(')===false);}else{check('test cart removal key found',false);}}
$r=req('android2','index.php?route=product/product&product_id=2147483647');check('unknown product does not produce server error',$r['row']['status']<500);
$report=array('checked_at_utc'=>gmdate('c'),'mode'=>'shared-approved-journal3','scope'=>'public guest sessions; mobile user agents; no account/order/payment','checks'=>$checks,'requests'=>$rows);file_put_contents(__DIR__.'/trinity-live-after-fixes.json',json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));chmod(__DIR__.'/trinity-live-after-fixes.json',0600);foreach(glob($dir.'/*.cookies') as $f)unlink($f);rmdir($dir);echo json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";
